export const dict = {
  ecografia: [
    "hipoecogênico",
    "hiperecogênico",
    "isoeicogênico",
    "aneico",
    "anecogênico",
    "sombra acústica posterior",
    "reverberação",
    "reforço acústico posterior",
    "artefato de cauda de cometa",
    "artefato em espelho",
    "nódulo sólido",
    "nódulo complexo",
    "lesão cística",
    "lesão septada",
    "vascularização periférica",
    "vascularização central",
    "fluxo de baixa resistência",
    "fluxo de alta resistência",
    "doppler colorido",
    "doppler pulsado",
    "índice de resistência (IR)",
    "pico sistólico (PSV)",
    "velocidade diastólica final (EDV)",
    "linfonodo reacional",
    "linfonodo suspeito",
    "microcalcificações",
    "calcificações grosseiras",
    "textura homogênea",
    "textura heterogênea",
    "margens irregulares",
    "cisto simples",
    "cisto complicado",
    "pseudocisto",
    "dilatação ductal",
    "sinal de Murphy positivo",
    "espessamento parietal",
    "cálculo biliar impactado",
    "cálculo renal",
    "hidronefrose",
    "dilatação pielocalicinal",
    "tireoide de ecotextura preservada",
    "micronódulos tireoidianos",
    "glândula salivar aumentada",
    "ascite",
    "hepatomegalia",
    "esplenomegalia",
    "sinal do alvo (US)",
    "nefrolitíase",
    "pielonefrite"
  ],
  tomografia: [
    "hiperdenso",
    "hipodenso",
    "isodenso",
    "realce heterogêneo",
    "realce homogêneo",
    "calcificação grosseira",
    "calcificação puntiforme",
    "padrão em vidro fosco",
    "opacidade consolidativa",
    "opacidades em mosaico",
    "bronquiectasias",
    "nódulo pulmonar espiculado",
    "nódulo sólido",
    "nódulo subsólido",
    "nódulo parcialmente sólido",
    "adenopatia mediastinal",
    "espessamento pleural",
    "espessamento septal interlobular",
    "favorecimento",
    "sinal do halo",
    "sinal do halo reverso",
    "padrão em pavimentação em mosaico",
    "árvore em brotamento",
    "micronódulos centrolobulares",
    "enfisema parasseptal",
    "enfisema centrolobular",
    "enfisema panlobular",
    "derrame pleural",
    "pneumotórax",
    "lesão hipovascular",
    "lesão hipervascular",
    "realce tardio",
    "nível hidroaéreo",
    "pneumomediastino",
    "densidade de gordura",
    "densidade de partes moles",
    "sinal do anel de sinete",
    "padrão em colmeia (honeycomb)",
    "pneumatocele",
    "bolhas enfisematosas",
    "atelectasia laminar",
    "bronquiolocele",
    "bronquiectasias de tração",
    "sinal da inversão da densidade",
    "cálculos biliares",
    "cálculos renais",
    "borramento da gordura perilesional",
    "sinal da alça sentinela",
    "opacidade em asa de morcego",
    "pneumonia organizada",
    "sinal do broncograma aéreo"
  ],
  ressonancia: [
    "hiperintenso em T2",
    "hipointenso em T2",
    "hiperintenso em T1",
    "hipointenso em T1",
    "isointenso",
    "restrição à difusão",
    "queda de sinal em T2",
    "queda de sinal em T1 com supressão de gordura",
    "realce tardio",
    "washout",
    "realce precoce",
    "hemossiderina",
    "degeneração mucóide",
    "artefato de suscetibilidade",
    "sequência FLAIR",
    "sequência STIR",
    "sequência DWI",
    "sequência ADC low-high",
    "sinal de flow void",
    "sequência GRE (Gradient-Echo)",
    "lipossupressão",
    "efeito de massa",
    "realce meníngeo",
    "realce dural",
    "realce leptomeníngeo",
    "restrição à difusão aparente",
    "hipersinal em T2/FLAIR",
    "padrão de realce nodular",
    "padrão de realce anelar",
    "padrão em roda dentada",
    "quociente ADC",
    "tempo de repetição (TR)",
    "tempo de eco (TE)",
    "impregnação anelar",
    "sinal de cisto de Tarlov",
    "sequência FSE (Fast Spin-Echo)",
    "sequência EPI (Echo-Planar Imaging)",
    "artefato de Gibbs",
    "artefato de movimento",
    "sinal de edema medular",
    "sinal do alvo (RM)",
    "massa com hipossinal em T1 e hipersinal em T2",
    "estudo dinâmico",
    "angio-RM"
  ],
  anatomia_geral: [
    "aorta abdominal",
    "artéria hepática",
    "veia porta",
    "artéria mesentérica superior",
    "veia cava inferior",
    "baço",
    "rim esquerdo",
    "rim direito",
    "lobo superior direito",
    "segmento VIII hepático",
    "istmo da tireoide",
    "lobo tireoidiano",
    "cabeça do pâncreas",
    "processo uncinado",
    "corpo do pâncreas",
    "corpo vertebral",
    "processo espinhoso",
    "forame intervertebral",
    "patela",
    "fêmur",
    "tíbia",
    "úmero",
    "cul-de-sac",
    "espaço de Morison",
    "fundo de saco de Douglas",
    "mesorreto",
    "córtex cerebral",
    "substância branca",
    "gânglios da base",
    "núcleo caudado",
    "putâmen",
    "globo pálido",
    "tálamo",
    "hipotálamo",
    "cerebelo",
    "tronco encefálico",
    "ventrículo lateral",
    "terceiro ventrículo",
    "quarto ventrículo",
    "cissura de Sylvius",
    "cisterna suprasselar",
    "tendão do supraespinhal",
    "menisco medial",
    "menisco lateral",
    "ligamento colateral medial",
    "ligamento cruzado anterior (LCA)",
    "ligamento cruzado posterior (LCP)"
  ],
  torax: [
    "nódulo pulmonar",
    "massa pulmonar",
    "atelectasia",
    "derrame pleural",
    "pneumotórax",
    "bronquiectasia",
    "espessamento septal",
    "padrão micronodular",
    "linfonodomegalia hilar",
    "infiltrado alveolar",
    "derrame pericárdico",
    "calcificação pericárdica",
    "mediastino alargado",
    "adenopatia subcarinal",
    "consolidação lobar",
    "opacidade reticular",
    "cissura espessada",
    "sinal da silhueta",
    "sinal do broncograma aéreo",
    "cavitação",
    "pneumonia organizada",
    "fibrose pulmonar",
    "padrão em vidro moído",
    "pneumonia intersticial não específica (PINE)",
    "pneumonia intersticial usual (PIU)",
    "bronquite crônica",
    "calcificação hilar",
    "opacidades nodulares calcificadas",
    "traqueomalácia",
    "aumento da área cardíaca"
  ],
  abdome: [
    "esteatose hepática",
    "hepatomegalia",
    "lesão focal hepática",
    "angioma hepático",
    "adenoma hepático",
    "hiperplasia nodular focal (HNF)",
    "dilatação das vias biliares",
    "colelitíase",
    "coledocolitíase",
    "pielonefrite",
    "nefrolitíase",
    "massa adrenal",
    "cisto de Bosniak I",
    "cisto de Bosniak IIF",
    "pancreatite aguda",
    "pancreatite crônica",
    "pseudocisto pancreático",
    "esplenomegalia",
    "ascite",
    "linfonodomegalia retroperitoneal",
    "trombose de veia porta",
    "colecistite aguda",
    "apendicite aguda",
    "diverticulite",
    "pneumoperitônio",
    "obstrução intestinal",
    "alça sentinela",
    "sinal do alvo (TC/US)",
    "intussuscepção",
    "íleo paralítico",
    "gases distribuídos",
    "elevação da cúpula diafragmática",
    "rim policístico"
  ],
  pelve: [
    "cisto ovariano",
    "folículo dominante",
    "corpo lúteo",
    "lesão anexial",
    "mioma subseroso",
    "mioma intramural",
    "mioma submucoso",
    "adenomiose",
    "prostatomegalia",
    "hiperplasia prostática benigna",
    "zona de transição",
    "zona periférica da próstata",
    "endometrioma",
    "cisto de Naboth",
    "hidrossalpinge",
    "dilatação piélica",
    "divertículo vesical",
    "espessamento endometrial",
    "endométrio atrófico",
    "cisto para-ovariano",
    "tumor de Brenner",
    "espectro de placenta acreta",
    "endometriose profunda",
    "líquido livre no fundo de saco",
    "sinal do 'rim' no tumor de ovário",
    "cisto hemorrágico"
  ],
  sistema_nervoso: [
    "lesão expansiva",
    "edema vasogênico",
    "edema citotóxico",
    "meninge realçada",
    "infarto agudo",
    "infarto subagudo",
    "infarto crônico",
    "gliose",
    "placas desmielinizantes",
    "microporos",
    "hemorragia subaracnoide",
    "hematoma subdural",
    "hematoma epidural",
    "hidrocefalia comunicante",
    "hidrocefalia não comunicante",
    "malformação arteriovenosa (MAV)",
    "aneurisma cerebral",
    "sinal da artéria hiperdensa",
    "desvio da linha média",
    "hernização uncal",
    "atrofia cortical",
    "sinal da dupla coroa",
    "sinal do ponto",
    "sinal da insula",
    "encefalomalácia",
    "leucoencefalopatia",
    "cavidade porencefálica",
    "cisto aracnoide",
    "tumores gliais",
    "metástase cerebral",
    "angioma cavernoso",
    "dissecção arterial cervical"
  ],
  musculoesqueletico: [
    "derrame articular",
    "condromalácia",
    "lesão de LCA",
    "lesão de LCP",
    "lesão do menisco medial",
    "lesão do menisco lateral",
    "lesão em alça de balde",
    "tenossinovite",
    "osteíte",
    "osteomielite",
    "fratura por estresse",
    "fratura patológica",
    "edema ósseo",
    "ruptura do manguito rotador",
    "tendinopatia",
    "bursite",
    "artrose",
    "espondilolistese",
    "hérnia discal",
    "protrusão discal",
    "extrusão discal",
    "degeneração mucoide",
    "cisto de Baker",
    "reação periosteal",
    "córtex insuflado",
    "padrão permeativo",
    "padrão geográfico",
    "triângulo de Codman",
    "esclerose subcondral",
    "osteófitos",
    "sinovite",
    "impingement femoroacetabular",
    "lesão labral",
    "atrofia muscular",
    "necrose avascular"
  ],
  vascular: [
    "estenose",
    "estenose crítica",
    "estenose suboclusiva",
    "trombose venosa profunda (TVP)",
    "trombose arterial",
    "dissecção aórtica",
    "aneurisma sacular",
    "aneurisma fusiforme",
    "oclusão",
    "pseudoaneurisma",
    "fístula arteriovenosa",
    "placa aterosclerótica",
    "placa calcificada",
    "varizes",
    "sinal de flow void",
    "fluxo turbulento",
    "onda trifásica",
    "onda bifásica",
    "onda monofásica",
    "calcificação parietal",
    "estenose carotídea",
    "vasoespasmo",
    "insuficiência venosa",
    "trombo mural",
    "dilatação aneurismática"
  ],
  procedimentos: [
    "punção aspirativa por agulha fina (PAAF)",
    "biópsia por agulha grossa (core biopsy)",
    "drenagem percutânea",
    "radioablação",
    "crioablação",
    "injeção intra-articular",
    "embolização",
    "quimioembolização (TACE)",
    "vertebroplastia",
    "cifoplastia",
    "nefrostomia",
    "angiografia",
    "cateterismo",
    "marcação pré-cirúrgica",
    "fluoroscopia",
    "artrografia",
    "colangiografia",
    "tomografia computadorizada de dupla energia (DECT)"
  ],
  patologias_gerais: [
    "carcinoma",
    "adenocarcinoma",
    "carcinoma de células escamosas",
    "hemangioma",
    "linfoma",
    "abscesso",
    "hematoma",
    "necrose",
    "necrose gordurosa",
    "cisto simples",
    "cisto complexo",
    "metástase",
    "fibrose",
    "inflamação",
    "granuloma",
    "lipoma",
    "teratoma",
    "sarcoma",
    "calcificação distrófica",
    "processo inflamatório crônico",
    "doença de Crohn",
    "colite ulcerativa",
    "tuberculose",
    "candidíase",
    "esclerose múltipla",
    "encefalite",
    "meningite",
    "artrite reumatoide",
    "lúpus eritematoso sistêmico",
    "amiloidose"
  ],
  
  // === PATOLOGIAS NEURORRADIOLÓGICAS ===
  patologias_neuro: [
    // VASCULARES
    "avc", "avci", "avch",
    "isquêmico", "isquêmica", "isquêmicos", "isquêmicas",
    "hemorrágico", "hemorrágica", "hemorrágicos", "hemorrágicas",
    "hematoma", "hematomas",
    "hemorragia", "hemorragias",
    "subdural", "epidural", "subaracnóidea", "subaracnoide",
    "intraparenquimatoso", "intraparenquimatosa",
    "aneurisma", "aneurismas",
    "malformação", "malformações",
    "arteriovenosa", "arteriovenosas",
    "cavernoma", "cavernomas",
    "angioma", "angiomas",
    "telangiectasia", "telangiectasias",
    "fístula", "fístulas",
    "trombose", "tromboses",
    "venosa", "venoso", "venosas", "venosos",
    "aterosclerose", "aterosclerótico", "aterosclerótica",
    "vasculite", "vasculites",
    "moyamoya",
    "dissecção", "dissecções",
    "vasospasmo",
    
    // TUMORES
    "glioma", "gliomas",
    "glioblastoma", "glioblastomas",
    "astrocitoma", "astrocitomas",
    "oligodendroglioma", "oligodendrogliomas",
    "ependimoma", "ependimomas",
    "meduloblastoma", "meduloblastomas",
    "meningioma", "meningiomas",
    "schwannoma", "schwannomas",
    "neurinoma", "neurinomas",
    "neurofibroma", "neurofibromas",
    "craniofaringioma", "craniofaringiomas",
    "adenoma", "adenomas",
    "hipofisário", "hipofisária", "hipofisários", "hipofisárias",
    "prolactinoma", "prolactinomas",
    "linfoma", "linfomas",
    "pinealoma", "pinealomas",
    "meduloepitelioma",
    "teratoma", "teratomas",
    "germinoma", "germinomas",
    "hemangioblastoma", "hemangioblastomas",
    
    // DESMIELINIZANTES
    "esclerose", "escleroses",
    "múltipla",
    "desmielinização", "desmielinizante", "desmielinizantes",
    "leucoencefalopatia", "leucoencefalopatias",
    "neuromielite",
    "óptica",
    "encefalomielite",
    "adrenoleucodistrofia",
    "leucodistrofia", "leucodistrofias",
    
    // INFECCIOSAS
    "encefalite", "encefalites",
    "meningite", "meningites",
    "meningoencefalite", "meningoencefalites",
    "cerebrite",
    "empiema", "empiemas",
    "toxoplasmose",
    "neurocisticercose", "cisticercose",
    "tuberculose", "tuberculoma", "tuberculomas",
    "neurotoxoplasmose",
    "herpes", "herpética", "herpético",
    "citomegalovírus",
    "leucoencefalopatia multifocal progressiva", "lemp",
    "prion", "creutzfeldt-jakob",
    
    // DEGENERATIVAS
    "alzheimer",
    "parkinson",
    "demência", "demências",
    "atrofia", "atrofias",
    "cortical", "corticais",
    "cerebelar",
    "hidrocefalia", "hidrocéfalo",
    "leucoaraiose",
    "gliose", "glioses",
    "encefalomalácia",
    "wallerian", "walleriana",
    "huntington",
    
    // CONGÊNITAS/MALFORMAÇÕES
    "malformação", "malformações",
    "arnold-chiari", "chiari",
    "dandy-walker",
    "agenesia", "agenesias",
    "hipoplasia", "hipoplasias",
    "holoprosencefalia",
    "lisencefalia",
    "paquigiria",
    "polimicrogiria",
    "heterotopia", "heterotopias",
    "esquizencefalia",
    "displasia", "displasias",
    "mielocele", "mielomeningocele",
    "lipoma", "lipomas",
    "dermoide", "dermoides",
    "epidermoide", "epidermoides",
    
    // COLUNA/MEDULA
    "hérnia", "hérnias",
    "discal", "discais",
    "protrusão", "protrusões",
    "extrusão", "extrusões",
    "espondilose",
    "espondilite",
    "espondilolistese",
    "espondilólise",
    "mielopatia", "mielopatias",
    "siringomielia", "siringomielias",
    "compressão", "compressões",
    "medular", "medulares",
    "radiculopatia", "radiculopatias",
    "estenose", "estenoses",
    "foraminal", "foraminais",
    
    // HIDROCEFALIA
    "ventriculomegalia",
    "hidrocefalia",
    "hidrocéfalo",
    "comunicante",
    "obstrutivo", "obstrutiva",
    "pressão normal",
    "derivação", "derivações"
  ],
  
  // === PATOLOGIAS DE CABEÇA E PESCOÇO ===
  patologias_cabeca_pescoco: [
    // ÓRBITA E GLOBO OCULAR
    "pseudotumor", "orbitário", "orbitária",
    "celulite", "pré-septal", "septal",
    "oftalmopatia", "graves",
    "dacrioadenite", "dacriocistite",
    "hemangioma capilar", "hemangioma cavernoso",
    "varizes", "linfangioma",
    "retinoblastoma", "melanoma", "uveal",
    "neurite", "óptica", "óptico",
    "proptose", "enoftalmia", "exoftalmia",
    
    // SEIOS PARANASAIS E CAVIDADE NASAL
    "sinusite", "rinossinusite",
    "maxilar", "etmoidal", "esfenoidal", "frontal",
    "pansinusite",
    "fúngica", "fúngico",
    "pólipo", "pólipos", "polipose", "polipoides",
    "papiloma", "invertido",
    "estesioneuroblastoma",
    "desvio", "septal", "perfuração",
    "granulomatose", "wegener",
    "aspergilose",
    
    // OSSO TEMPORAL E ORELHA
    "colesteatoma", "colesteatomas",
    "otite", "média", "crônica",
    "otomastoidite", "mastoidite",
    "timpanoesclerose",
    "otosclerose",
    "labirintite",
    "vestibular", "vestibulares",
    "neuroma", "acústico",
    "ménière",
    "paraganglioma", "paragangliomas",
    "glomus", "jugular", "timpânico",
    "atresia", "auditivo",
    "mondini",
    "aqueduto", "alargado",
    
    // GLÂNDULAS SALIVARES
    "sialadenite", "sialolitíase",
    "parotidite", "submandibulite",
    "pleomórfico", "pleomórfica",
    "warthin",
    "oncocitoma",
    "linfoepitelial",
    "mucoepidermoide",
    "acinares",
    "sialose",
    "sjögren",
    "rânula",
    
    // FARINGE E CAVIDADE ORAL
    "nasofaringe", "orofaringe", "hipofaringe",
    "assoalho", "bucal",
    "peritonsilar", "retrofaríngeo", "parafaríngeo",
    "tornwaldt",
    "angioedema",
    "tonsilite", "faringite",
    "mononucleose",
    
    // LARINGE
    "vocal", "vocais",
    "papilomatose",
    "laringocele",
    "glótico", "glótica",
    "supraglótico", "supraglótica",
    "subglótico", "subglótica",
    "transglótico", "transglótica",
    "reinke",
    "laringite",
    
    // TIREOIDE E PARATIREOIDES
    "tireoidiano", "tireoidiana",
    "bócio", "multinodular",
    "coloide", "coloides",
    "folicular", "foliculares",
    "hashimoto",
    "papilífero", "papilífera",
    "medular", "medulares",
    "anaplásico", "anaplásica",
    "paratireoide", "paratireoides",
    
    // ESPAÇOS CERVICAIS PROFUNDOS
    "branquial", "branquiais",
    "tireoglosso",
    "higroma",
    "carotídea", "carotídeo", "carotídeas",
    "corpo carotídeo",
    
    // LINFONODOS CERVICAIS
    "linfadenopatia", "reativa",
    "linfadenite",
    "tuberculose ganglionar",
    "linfonodal", "linfonodais",
    "hodgkin",
    "extracapsular",
    "conglomerado"
  ],
  
  rads_scores: [
    "BI-RADS 0", "BI-RADS 1", "BI-RADS 2", "BI-RADS 3", "BI-RADS 4A", "BI-RADS 4B", "BI-RADS 4C", "BI-RADS 5", "BI-RADS 6",
    "TI-RADS 1", "TI-RADS 2", "TI-RADS 3", "TI-RADS 4", "TI-RADS 5",
    "PI-RADS 1", "PI-RADS 2", "PI-RADS 3", "PI-RADS 4", "PI-RADS 5",
    "LI-RADS 1", "LI-RADS 2", "LI-RADS 3", "LI-RADS 4", "LI-RADS 5", "LI-RADS TIV", "LI-RADS M",
    "O-RADS 1", "O-RADS 2", "O-RADS 3", "O-RADS 4", "O-RADS 5",
    "Lung-RADS 1", "Lung-RADS 2", "Lung-RADS 3", "Lung-RADS 4A", "Lung-RADS 4B", "Lung-RADS 4X",
    "CAD-RADS 0", "CAD-RADS 1", "CAD-RADS 2", "CAD-RADS 3", "CAD-RADS 4", "CAD-RADS 5",
    "C-RADS", "NI-RADS", "VIR-RADS"
  ],
  termos_quantitativos: [
    "aumentado",
    "reduzido",
    "espessado",
    "afinamento",
    "assimétrico",
    "simétrico",
    "volumoso",
    "dimensões preservadas",
    "> 1 cm",
    "< 1 cm",
    "> 10 mm",
    "< 10 mm",
    "medindo",
    "centimetrado",
    "milimetrado",
    "discreto",
    "moderado",
    "acentuado",
    "extenso",
    "focal",
    "difuso",
    "global",
    "parcial",
    "significativo",
    "mínimo",
    "leve",
    "acima do percentil 95"
  ],
  termos_descricao: [
    "heterogêneo",
    "homogêneo",
    "regular",
    "irregular",
    "bem delimitado",
    "mal delimitado",
    "lobulado",
    "espiculado",
    "indefinido",
    "circunscrito",
    "serpiginoso",
    "marginal",
    "hipoecogênico",
    "hiperecogênico",
    "hiperdenso",
    "hipodenso",
    "cístico",
    "sólido",
    "complexo",
    "multi-septado",
    "septado",
    "liso",
    "rugoso",
    "pedunculado",
    "séssil",
    "microlobulado",
    "macrolobulado",
    "polipoide",
    "móvel",
    "fixo",
    "redondo",
    "ovalado",
    "fusiforme",
    "amórfico",
    "linear"
  ],
  portugues_laudo: [
    // === VERBOS COMUNS EM LAUDOS ===
    "realizado", "realizada", "realizados", "realizadas",
    "apresenta", "apresentam", "apresentando",
    "observa", "observado", "observada", "observados", "observadas", "observando",
    "demonstra", "demonstrando", "demonstrado", "demonstrada",
    "evidencia", "evidenciado", "evidenciada", "evidenciando", "evidências",
    "mostra", "mostrando", "mostrado", "mostrada",
    "sugere", "sugerindo", "sugestivo", "sugestiva",
    "pode", "podem", "poderá", "poderão", "podendo",
    "indica", "indicando", "indicado", "indicada",
    "permite", "permitindo", "permitido",
    "exclui", "excluir", "excluído", "excluída",
    "confirma", "confirmado", "confirmada", "confirmando",
    "caracteriza", "caracterizado", "caracterizada",
    "mede", "medindo", "medido", "medida",
    "localiza", "localizado", "localizada",
    "apresentar", "observar", "demonstrar", "evidenciar",
    
    // === SUBSTANTIVOS COMUNS ===
    "exame", "exames", "estudo", "estudos",
    "aspecto", "aspectos", "ausência", "presença",
    "região", "regiões", "área", "áreas",
    "dimensões", "dimensão", "limites", "limite",
    "contornos", "contorno", "margens", "margem",
    "planos", "plano", "cortes", "corte",
    "incidências", "incidência", "projeções", "projeção",
    "achados", "achado", "alterações", "alteração",
    "sinais", "sinal", "imagens", "imagem",
    "lesão", "lesões", "intensidade", "intensidades",
    "avaliação", "análise", "comparação",
    "contraste", "controle", "seguimento",
    "técnica", "método", "protocolo",
    "estruturas", "estrutura", "órgãos", "órgão",
    "sistema", "sistemas", "aparelho",
    "informações", "informação", "dados", "dado",
    "conclusão", "impressão", "opinião",
    "hipótese", "diagnóstico", "diagnósticos",
    "paciente", "examinado", "examinada",
    "ano", "anos", "mês", "meses", "dia", "dias",
    "lado", "lados", "porção", "porções",
    "terço", "terços", "metade",
    "densidade", "densidades",
    "tamanho", "forma", "posição",
    
    // === ADJETIVOS COMUNS ===
    "normal", "normais", "habitual", "habituais",
    "preservado", "preservada", "preservados", "preservadas",
    "característica", "características", "característico", "característicos",
    "compatível", "compatíveis", "sugestivo", "sugestiva",
    "típico", "típica", "típicos", "típicas",
    "atípico", "atípica", "atípicos", "atípicas",
    "usual", "incomum", "frequente", "raro", "rara",
    "bilateral", "bilaterais", "unilateral", "unilaterais",
    "anterior", "posterior", "superior", "inferior",
    "medial", "lateral", "proximal", "distal",
    "direito", "direita", "esquerdo", "esquerda",
    "pequeno", "pequena", "pequenos", "pequenas",
    "grande", "grandes", "médio", "média", "médios", "médias",
    "alto", "alta", "altos", "altas",
    "baixo", "baixa", "baixos", "baixas",
    "bom", "boa", "bons", "boas",
    "mau", "má", "maus", "más",
    "livre", "livres", "restrito", "restrita",
    "adequado", "adequada", "inadequado", "inadequada",
    "presente", "presentes", "ausente", "ausentes",
    "novo", "nova", "novos", "novas",
    "antigo", "antiga", "antigos", "antigas",
    "recente", "recentes", "prévio", "prévia",
    "adicional", "adicionais", "complementar", "complementares",
    "principal", "principais", "secundário", "secundária",
    "único", "única", "únicos", "únicas",
    "múltiplo", "múltipla", "múltiplos", "múltiplas",
    "denso", "densa", "densos", "densas",
    "espesso", "espessa", "fino", "fina",
    "profundo", "profunda", "superficial",
    "central", "periférico", "periférica",
    
    // === CONECTIVOS E PREPOSIÇÕES ===
    "que", "qual", "quais", "como", "onde",
    "com", "sem", "para", "por", "entre",
    "sobre", "sob", "após", "antes",
    "durante", "através", "mediante",
    "conforme", "segundo", "devido",
    "além", "inclusive", "exceto",
    
    // === ADVÉRBIOS ===
    "não", "sim", "bem", "mal",
    "mais", "menos", "muito", "pouco",
    "apenas", "somente", "principalmente",
    "parcialmente", "completamente", "totalmente",
    "provavelmente", "possivelmente", "certamente",
    "aparentemente", "relativamente", "aproximadamente",
    "tipicamente", "usualmente", "normalmente",
    "eventualmente", "ocasionalmente", "raramente",
    
    // === ARTIGOS E PRONOMES ===
    "este", "esta", "estes", "estas",
    "esse", "essa", "esses", "essas",
    "aquele", "aquela", "aqueles", "aquelas",
    "seu", "sua", "seus", "suas",
    "mesmo", "mesma", "mesmos", "mesmas",
    "outro", "outra", "outros", "outras",
    "todo", "toda", "todos", "todas",
    "cada", "alguns", "algumas", "nenhum", "nenhuma",
    
    // === NÚMEROS ORDINAIS ===
    "primeiro", "primeira", "segundo", "segunda",
    "terceiro", "terceira", "quarto", "quarta",
    
    // === TERMOS TÉCNICOS GERAIS ===
    "digital", "analógico", "computadorizado",
    "intravenoso", "intravenosa", "oral",
    "mamográfico", "mamográfica", "mamografia",
    "ultrassonografia", "ultrassonográfico", "ultrassonográfica",
    "tomográfico", "tomográfica",
    "radiográfico", "radiográfica", "radiografia",
    "ocultar", "oculto", "oculta", "obscurecer",
    "trazer", "traz", "trazendo",
    "indicar", "indicando",
    "rastreamento", "screening",
    "categoria", "categorias", "classificação",
    
    // === TERMOS ANATÔMICOS DE USO GERAL ===
    "mama", "mamas", "axilar", "axilares",
    "mamário", "mamária", "tecido",
    "glandular", "adiposo", "fibroglandular",
    "nódulo", "nódulos", "calcificação", "calcificações",
    "benigno", "benigna", "benignas", "benignos",
    "maligno", "maligna", "malignas", "malignos",
    "patológico", "patológica",
    "parênquima", "estroma",
    "esparsas", "dispersas", "agrupadas"
  ],
  
  // === CATEGORIA: TERMOS EXTRAÍDOS DE TEMPLATES E FRASES DO BANCO SUPABASE ===
  termos_templates_supabase: [
    // === ANATOMIA ABDOMINAL ===
    "fígado", "hepático", "hepática", "hepáticos", "hepáticas",
    "parenquimatosa", "parenquimatoso",
    "vesícula", "vesicular", "biliar", "biliares",
    "colédoco", "hepatocolédoco", "cístico",
    "pâncreas", "pancreático", "pancreática",
    "ducto", "ductos", "ductais", "ductal",
    "baço", "esplênico", "esplênica",
    "adrenais", "adrenal",
    "rins", "rim", "renal", "renais",
    "bexiga", "vesical",
    "intestino", "intestinal", "intestinais",
    "alças", "delgadas", "delgado",
    "cólon", "cólica", "cólico",
    "reto", "retal",
    "duodeno", "duodenal",
    "estômago", "gástrico", "gástrica",
    "aorta", "aórtico", "aórtica", "aórticos",
    "veia", "veias", "venoso", "venosa", "venosos", "venosas",
    "cava", "porta", "portais", "portal",
    "artéria", "artérias", "arterial", "arteriais",
    "mesentérica", "mesentérico",
    "ilíaca", "ilíaco", "ilíacas",
    "retroperitoneal", "retroperitoneais", "retroperitônio",
    "peritônio", "peritoneal",
    "cavidade", "abdominal", "abdominais",
    
    // === ANATOMIA TORÁCICA ===
    "pulmão", "pulmões", "pulmonar", "pulmonares",
    "pleura", "pleural", "pleurais",
    "mediastino", "mediastinal", "mediastinais",
    "traqueia", "traqueal",
    "brônquios", "brônquio", "brônquico", "brônquica",
    "costais", "costal", "arcos",
    "diafragma", "diafragmático", "diafragmática",
    "cardíaco", "cardíaca", "cardíacos",
    "pericárdio", "pericárdico",
    
    // === ANATOMIA NEUROLÓGICA ===
    "cérebro", "cerebral", "cerebrais",
    "cerebelo", "cerebelar", "cerebelares",
    "hemisférios", "hemisfério",
    "ventrículos", "ventrículo", "ventricular",
    "substância", "substâncias",
    "cinzenta", "branca",
    "córtex", "cortical", "corticais", "subcortical",
    "sulcos", "sulcação",
    "giros", "giro",
    "meninges", "meníngeo", "meníngea",
    "dural", "durais",
    "medula", "medular", "medulares",
    "espinhal", "raquiano", "raquidiano",
    "nervos", "nervo", "nervoso", "nervosa",
    "tronco", "encefálico",
    "hipófise", "hipofisária", "hipofisário",
    "selar", "sela", "túrcica",
    "órbitas", "orbitário", "orbitária",
    "globos", "oculares", "ocular",
    
    // === ANATOMIA MUSCULOESQUELÉTICA ===
    "vértebras", "vértebra", "vertebral", "vertebrais",
    "discos", "disco", "discal", "discais", "intervertebrais",
    "coluna", "cervical", "torácica", "lombar", "sacral",
    "sacro", "sacroilíacas", "coccígeas", "coccígeos",
    "articulações", "articular", "articulares",
    "facetárias", "interapofisárias",
    "ligamentos", "ligamento", "ligamentares",
    "tendões", "tendão", "tendinoso", "tendinosa",
    "músculos", "músculo", "muscular", "musculares",
    "osso", "ossos", "ósseo", "óssea", "ósseas",
    "meniscos", "menisco",
    "cartilagem", "cartilaginoso", "cartilaginosa",
    "labrum", "labral",
    "superfícies", "superfície",
    "epífises", "epífise", "epifisário",
    
    // === ANATOMIA PELVE ===
    "útero", "uterino", "uterina", "uterinos",
    "ovários", "ovário", "ovariano", "ovariana",
    "anexos", "anexiais", "anexial",
    "endométrio", "endometrial",
    "miométrio", "miometrial",
    "cérvix",
    "vagina", "vaginal",
    "próstata", "prostático", "prostática", "prostáticos",
    "seminais", "seminal",
    "testículos", "testículo", "testicular",
    "epidídimo", "epidídimos",
    "funículo", "espermático",
    
    // === ANATOMIA MAMA ===
    "mama", "mamas", "mamário", "mamária", "mamários", "mamárias",
    "fibroglandular", "glandular",
    "retroglandular", "subglandular",
    "axilar", "axilares", "axila",
    "areolopapilares", "areolar",
    "peitoral", "retropeitoral",
    
    // === ANATOMIA VASCULAR ===
    "carótida", "carótidas", "carotídeo", "carotídeos", "carotídeas",
    "subclávia", "subclávias",
    "jugulares", "jugular",
    "braquiocefálico",
    "vertebrobasilar",
    "femorais", "femoral",
    "poplítea", "poplíteo",
    "tibiais", "tibial",
    "fibular", "fibulares",
    "pediosa",
    
    // === DESCRITORES MORFOLÓGICOS ===
    "calibre", "calibres",
    "contornos", "bordos", "bordas", "margens",
    "regulares", "irregulares",
    "lisos", "lisas", "serrilhados",
    "finos", "finas",
    "espessura", "espessamento",
    "morfologia", "configuração",
    "trajeto", "percurso",
    "topografia", "tópico", "tópicos", "tópica",
    "posicionado", "posicionados", "normoposicionado", "normoposicionados",
    
    // === DESCRITORES DE SINAL/DENSIDADE ===
    "ecotextura", "ecogenicidade",
    "hiperecogênica", "hiperecogênico", "hiperecogênicas",
    "hipoecogênica", "hipoecogênico", "hipoecogênicas",
    "anecoico", "anecóico", "anecoica",
    "isoecogênico", "isoecogênica",
    "hipointenso", "hiperintenso", "isointenso",
    "hipodenso", "hiperdenso", "isodenso",
    "atenuação",
    
    // === DESCRITORES DE ESTADO/CONDIÇÃO ===
    "íntegro", "íntegra", "íntegros", "íntegras",
    "pérvio", "pérvia", "pérvios", "pérvias",
    "patente", "patentes",
    "normodistendido", "normodistendida",
    "distendido", "distendida", "distensão", "distensibilidade",
    "repleção", "repleto", "repleta",
    "colabado", "colabada",
    "dilatado", "dilatada", "dilatação", "dilatações",
    
    // === DESCRITORES NEGATIVOS ===
    "excluir", "excluído", "excluída",
    "descartado", "descartada",
    "afastado", "afastada",
    
    // === ACHADOS/LESÕES ===
    "lesional",
    "focais", "focalmente",
    "difuso", "difusa", "difusos", "difusas",
    "nodular", "nodulares",
    "cistos", "císticos", "císticas",
    "calcificações", "calcificado", "calcificada",
    "microcalcificações",
    "cálculo", "cálculos", "calculosa", "calculosas", "calculoso",
    
    // === TERMOS TÉCNICOS DE EXAME ===
    "sequências", "sequência",
    "multiplanares", "multiplanar",
    "ponderadas", "ponderado", "ponderada",
    "contrastado", "contrastada", "contrastação",
    "paramagnético", "paramagnética",
    "endovenoso", "endovenosa",
    "hepatoespecífico",
    "primovist",
    "gadolínio",
    "iodado",
    "excretora", "excretor",
    "perfusional",
    "difusão", "difusional",
    "angio", "angiorressonância", "angiografia",
    
    // === VERBOS MÉDICOS ESPECÍFICOS ===
    "medem", "medindo",
    "evidenciamos",
    "identifica", "identificado", "identificada", "identificando",
    "caracterizando",
    "demonstrou",
    "observadas",
    "revela", "revelando", "revelado",
    "exibe", "exibindo",
    "nota", "notando",
    "sugestivos",
    "correlacionar", "correlacionado",
    
    // === LOCALIZAÇÃO ===
    "intra", "extra", "peri", "para", "retro", "sub", "supra",
    "intrahepático", "extrahepático",
    "intra-hepáticas", "extra-hepáticas",
    "intracraniano", "intracraniana",
    "intraperitoneal",
    "subcapsular", "extracapsular",
    "periféricos",
    "centrais",
    "proximais",
    "distais",
    "mediais",
    "laterais",
    "anteriores",
    "posteriores",
    "superiores",
    "inferiores",
    
    // === TERMOS DE LAUDO ===
    "limites", "normalidade",
    "complementação",
    "particularidades",
    "métodos",
    "critério", "clínicos",
    
    // === PATOLOGIAS ESPECÍFICAS ===
    "linfonodomegalia", "linfonodomegalias",
    "linfonopatia", "linfonodopatia", "linfonodopatias",
    "linfonodos", "linfonodo",
    "adenopatia", "adenopatias",
    "esteatose", "esteatótico",
    "cirrose", "cirrótico", "cirrótica",
    "hepatopatia",
    "colelitíase", "coledocolitíase",
    "colecistite",
    "pancreatite",
    "pielonefrite",
    "hidronefrose", "pielocalicinal",
    "trombose", "trombo", "trombos",
    "estenose", "estenoses", "estenosado",
    "oclusão", "oclusões", "ocluído",
    "aneurisma", "aneurismas", "aneurismáticas",
    "dissecção", "dissecções",
    "hérnia", "hérnias", "herniado", "herniada",
    "protrusão", "protrusões",
    "fratura", "fraturas",
    "edema", "edematoso", "edematosa",
    "fibrose", "fibrótico", "fibrótica",
    "atrofia", "atrófico", "atrófica",
    
    // === UNIDADES E MEDIDAS ===
    "hu",
    "diâmetro", "diâmetros",
    "eixo", "eixos",
    "volumétrico",
    
    // === TERMOS ESPECÍFICOS POR MODALIDADE ===
    "flair", "stir", "dwi", "adc",
    "t1", "t2",
    "washout", "realce",
    "impregnação",
    "hounsfield", "agatston",
    "janela", "janelas",
    "sombra", "acústica", "acústico",
    "doppler", "fluxo",
    "reforço",
    "artefato", "artefatos",
    "murphy",
    
    // === TERMOS OBSTÉTRICOS ===
    "feto", "fetal", "fetais",
    "gestação", "gestacional",
    "placentário", "placenta",
    "líquido", "amniótico",
    "cordão", "umbilical",
    
    // === OUTROS TERMOS FREQUENTES ===
    "aparentes",
    "avaliado", "avaliada", "avaliados", "avaliadas",
    "padrão", "padrões",
    "distribuição",
    "relação", "proporção",
    "conjunto", "contexto",
    "decorrente", "decorrentes",
    "secundários",
    "eventualmente",
    "sobretudo",
    "poderão",
    "cpre", "colangiorm",
    "ramos", "paredes", "conteúdo", "homogêneo", "meio", "concentração", "conservados", "vias",
    
    // === ANATOMIA/ESTRUTURAS ADICIONAIS ===
    "forma", "formas",
    "arquitetura", "arquitetural",
    "arco", "troncos",
    "bulbo", "bulbos",
    "lobo", "lobos",
    "segmento", "segmentos",
    "espaços",
    "intercostal", "intercostais",
    "membro", "membros",
    "leito",
    
    // === DESCRITORES DE ESTADO/VISUALIZAÇÃO ===
    "visibilizado", "visibilizada", "visibilizados", "visibilizadas",
    "mantido", "mantida", "mantidos",
    "comum", "comuns",
    "interno", "interna", "internos", "internas",
    "significativo", "significativa", "significativos", "significativas",
    "indeterminado", "indeterminada", "indeterminados",
    "acentuado", "acentuada", "acentuados", "acentuadas",
    "rombo", "rombos",
    "maldefinido", "maldefinidos", "maldefinida", "maldefinidas",
    "gorduroso", "gordurosa", "gordurosos", "gordurosas",
    "crônico", "crônica", "crônicos", "crônicas",
    "reduzido", "reduzida", "reduzidos", "reduzidas",
    "solitário", "solitária", "solitários", "solitárias",
    "suspeito", "suspeita", "suspeitos", "suspeitas",
    "comprometido", "comprometida", "comprometidos", "comprometidas", "comprometendo",
    
    // === TERMOS TÉCNICOS DE EXAME ===
    "simetria", "simétrico", "simétrica",
    "alinhamento", "alinhado", "alinhada",
    "aeração",
    "vascularização",
    "restrição",
    "infiltração", "infiltrado", "infiltrada",
    "depósito", "depósitos",
    "extensão",
    "fator", "fatores",
    "obstrutivo", "obstrutiva", "obstrutivos",
    "feixe",
    "grau", "graus",
    "bilateralmente",
    "difusamente",
    
    // === MODALIDADES E TÉCNICAS ===
    "tomografia",
    "ressonância",
    "magnética", "magnético",
    "computadorizada", "computadorizado",
    "convencional",
    "colangiorressonância",
    
    // === STATUS E CONDIÇÕES ===
    "status",
    "cirúrgico", "cirúrgica", "cirúrgicos",
    "pós-cirúrgico", "pós-cirúrgica",
    "pós-colecistectomia",
    
    // === PATOLOGIAS ADICIONAIS ===
    "hemangioma", "hemangiomas",
    
    // === SUBSTÂNCIAS (DOENÇAS DE DEPÓSITO) ===
    "ferro",
    "glicogênio",
    "cobre",
    
    // === OUTROS TERMOS FREQUENTES NOS TEMPLATES ===
    "pacs",
    "ortostase",
    "curva", "curvas",
    "fisiológico", "fisiológica", "fisiológicos", "fisiológicas",
    "laudo", "laudos",
    "elaborado", "elaborada",
    "base", "bases",
    "cerca",
    "disponível", "disponíveis",
    "custa",
    "massas"
  ],
  
  sinonimos: {
    aneico: ["anecogênico", "sonolucente", "líquido simples", "conteúdo fluídico"],
    hipoecogênico: ["hipoecóico", "escuro ao ultrassom"],
    hiperecogênico: ["hiperecóico", "brilhante ao ultrassom"],
    hipodenso: ["baixa atenuação", "hipoatenuante", "radiotransparente"],
    hiperdenso: ["alta atenuação", "hiperatenuante", "radiopaco"],
    isodenso: ["isoatenuante"],
    "esteatose hepática": ["fígado gorduroso", "infiltração gordurosa hepática"],
    "derrame pleural": ["efusão pleural", "coleção líquida pleural"],
    "líquido livre": ["ascite", "coleção peritoneal", "efusão abdominal", "líquido ascítico"],
    HNF: ["hiperplasia nodular focal"],
    "placas desmielinizantes": ["lesões de substância branca", "lesões focais brancas"],
    TVP: ["trombose venosa profunda", "flebotrombose"],
    slice: ["corte tomográfico", "fatia de imagem", "corte"],
    quisto: ["cisto", "quiste"],
    "restrição à difusão": ["queda de sinal no mapa ADC e hipersinal no DWI"],
    "flow void": ["ausência de sinal vascular", "sinal de vazio de fluxo"],
    angiografia: ["estudo radiográfico dos vasos", "arteriografia", "venografia"],
    "TC helicoidal": ["tomografia computadorizada com órbita helicoidal", "TC volumétrica"],
    Ultrassonografia: ["ecografia", "US", "sonografia", "ultrassom"],
    pneumoperitônio: ["gás livre subdiafragmático", "pneumatose"],
    atelectasia: ["colapso pulmonar"],
    artrose: ["osteoartrite", "doença articular degenerativa"],
    osteófitos: ["bicos de papagaio"],
    "edema ósseo": ["contusão óssea", "aumento de sinal na medular óssea"],
    gliose: ["sequela isquêmica", "cicatriz cerebral"],
    micronódulo: ["nódulo pequeno"],
    adenopatia: ["linfonodomegalia"],
    calcificação: ["depósito de cálcio"],
    "necrose avascular": ["osteonecrose"]
  }
} as const

