export const dict = {
  ecografia: [
    "hipoecogênico",
    "hiperecogênico",
    "isoeicogênico",
    "aneico",
    "anecogênico",
    "sombra acústica posterior",
    "reverberação",
    "reforço acústico posterior",
    "artefato de cauda de cometa",
    "artefato em espelho",
    "nódulo sólido",
    "nódulo complexo",
    "lesão cística",
    "lesão septada",
    "vascularização periférica",
    "vascularização central",
    "fluxo de baixa resistência",
    "fluxo de alta resistência",
    "doppler colorido",
    "doppler pulsado",
    "índice de resistência (IR)",
    "pico sistólico (PSV)",
    "velocidade diastólica final (EDV)",
    "linfonodo reacional",
    "linfonodo suspeito",
    "microcalcificações",
    "calcificações grosseiras",
    "textura homogênea",
    "textura heterogênea",
    "margens irregulares",
    "cisto simples",
    "cisto complicado",
    "pseudocisto",
    "dilatação ductal",
    "sinal de Murphy positivo",
    "espessamento parietal",
    "cálculo biliar impactado",
    "cálculo renal",
    "hidronefrose",
    "dilatação pielocalicinal",
    "tireoide de ecotextura preservada",
    "micronódulos tireoidianos",
    "glândula salivar aumentada",
    "ascite",
    "hepatomegalia",
    "esplenomegalia",
    "sinal do alvo (US)",
    "nefrolitíase",
    "pielonefrite"
  ],
  tomografia: [
    "hiperdenso",
    "hipodenso",
    "isodenso",
    "realce heterogêneo",
    "realce homogêneo",
    "calcificação grosseira",
    "calcificação puntiforme",
    "padrão em vidro fosco",
    "opacidade consolidativa",
    "opacidades em mosaico",
    "bronquiectasias",
    "nódulo pulmonar espiculado",
    "nódulo sólido",
    "nódulo subsólido",
    "nódulo parcialmente sólido",
    "adenopatia mediastinal",
    "espessamento pleural",
    "espessamento septal interlobular",
    "favorecimento",
    "sinal do halo",
    "sinal do halo reverso",
    "padrão em pavimentação em mosaico",
    "árvore em brotamento",
    "micronódulos centrolobulares",
    "enfisema parasseptal",
    "enfisema centrolobular",
    "enfisema panlobular",
    "derrame pleural",
    "pneumotórax",
    "lesão hipovascular",
    "lesão hipervascular",
    "realce tardio",
    "nível hidroaéreo",
    "pneumomediastino",
    "densidade de gordura",
    "densidade de partes moles",
    "sinal do anel de sinete",
    "padrão em colmeia (honeycomb)",
    "pneumatocele",
    "bolhas enfisematosas",
    "atelectasia laminar",
    "bronquiolocele",
    "bronquiectasias de tração",
    "sinal da inversão da densidade",
    "cálculos biliares",
    "cálculos renais",
    "borramento da gordura perilesional",
    "sinal da alça sentinela",
    "opacidade em asa de morcego",
    "pneumonia organizada",
    "sinal do broncograma aéreo"
  ],
  ressonancia: [
    "hiperintenso em T2",
    "hipointenso em T2",
    "hiperintenso em T1",
    "hipointenso em T1",
    "isointenso",
    "restrição à difusão",
    "queda de sinal em T2",
    "queda de sinal em T1 com supressão de gordura",
    "realce tardio",
    "washout",
    "realce precoce",
    "hemossiderina",
    "degeneração mucóide",
    "artefato de suscetibilidade",
    "sequência FLAIR",
    "sequência STIR",
    "sequência DWI",
    "sequência ADC low-high",
    "sinal de flow void",
    "sequência GRE (Gradient-Echo)",
    "lipossupressão",
    "efeito de massa",
    "realce meníngeo",
    "realce dural",
    "realce leptomeníngeo",
    "restrição à difusão aparente",
    "hipersinal em T2/FLAIR",
    "padrão de realce nodular",
    "padrão de realce anelar",
    "padrão em roda dentada",
    "quociente ADC",
    "tempo de repetição (TR)",
    "tempo de eco (TE)",
    "impregnação anelar",
    "sinal de cisto de Tarlov",
    "sequência FSE (Fast Spin-Echo)",
    "sequência EPI (Echo-Planar Imaging)",
    "artefato de Gibbs",
    "artefato de movimento",
    "sinal de edema medular",
    "sinal do alvo (RM)",
    "massa com hipossinal em T1 e hipersinal em T2",
    "estudo dinâmico",
    "angio-RM"
  ],
  anatomia_geral: [
    "aorta abdominal",
    "artéria hepática",
    "veia porta",
    "artéria mesentérica superior",
    "veia cava inferior",
    "baço",
    "rim esquerdo",
    "rim direito",
    "lobo superior direito",
    "segmento VIII hepático",
    "istmo da tireoide",
    "lobo tireoidiano",
    "cabeça do pâncreas",
    "processo uncinado",
    "corpo do pâncreas",
    "corpo vertebral",
    "processo espinhoso",
    "forame intervertebral",
    "patela",
    "fêmur",
    "tíbia",
    "úmero",
    "cul-de-sac",
    "espaço de Morison",
    "fundo de saco de Douglas",
    "mesorreto",
    "córtex cerebral",
    "substância branca",
    "gânglios da base",
    "núcleo caudado",
    "putâmen",
    "globo pálido",
    "tálamo",
    "hipotálamo",
    "cerebelo",
    "tronco encefálico",
    "ventrículo lateral",
    "terceiro ventrículo",
    "quarto ventrículo",
    "cissura de Sylvius",
    "cisterna suprasselar",
    "tendão do supraespinhal",
    "menisco medial",
    "menisco lateral",
    "ligamento colateral medial",
    "ligamento cruzado anterior (LCA)",
    "ligamento cruzado posterior (LCP)"
  ],
  torax: [
    "nódulo pulmonar",
    "massa pulmonar",
    "atelectasia",
    "derrame pleural",
    "pneumotórax",
    "bronquiectasia",
    "espessamento septal",
    "padrão micronodular",
    "linfonodomegalia hilar",
    "infiltrado alveolar",
    "derrame pericárdico",
    "calcificação pericárdica",
    "mediastino alargado",
    "adenopatia subcarinal",
    "consolidação lobar",
    "opacidade reticular",
    "cissura espessada",
    "sinal da silhueta",
    "sinal do broncograma aéreo",
    "cavitação",
    "pneumonia organizada",
    "fibrose pulmonar",
    "padrão em vidro moído",
    "pneumonia intersticial não específica (PINE)",
    "pneumonia intersticial usual (PIU)",
    "bronquite crônica",
    "calcificação hilar",
    "opacidades nodulares calcificadas",
    "traqueomalácia",
    "aumento da área cardíaca"
  ],
  abdome: [
    "esteatose hepática",
    "hepatomegalia",
    "lesão focal hepática",
    "angioma hepático",
    "adenoma hepático",
    "hiperplasia nodular focal (HNF)",
    "dilatação das vias biliares",
    "colelitíase",
    "coledocolitíase",
    "pielonefrite",
    "nefrolitíase",
    "massa adrenal",
    "cisto de Bosniak I",
    "cisto de Bosniak IIF",
    "pancreatite aguda",
    "pancreatite crônica",
    "pseudocisto pancreático",
    "esplenomegalia",
    "ascite",
    "linfonodomegalia retroperitoneal",
    "trombose de veia porta",
    "colecistite aguda",
    "apendicite aguda",
    "diverticulite",
    "pneumoperitônio",
    "obstrução intestinal",
    "alça sentinela",
    "sinal do alvo (TC/US)",
    "intussuscepção",
    "íleo paralítico",
    "gases distribuídos",
    "elevação da cúpula diafragmática",
    "rim policístico"
  ],
  pelve: [
    "cisto ovariano",
    "folículo dominante",
    "corpo lúteo",
    "lesão anexial",
    "mioma subseroso",
    "mioma intramural",
    "mioma submucoso",
    "adenomiose",
    "prostatomegalia",
    "hiperplasia prostática benigna",
    "zona de transição",
    "zona periférica da próstata",
    "endometrioma",
    "cisto de Naboth",
    "hidrossalpinge",
    "dilatação piélica",
    "divertículo vesical",
    "espessamento endometrial",
    "endométrio atrófico",
    "cisto para-ovariano",
    "tumor de Brenner",
    "espectro de placenta acreta",
    "endometriose profunda",
    "líquido livre no fundo de saco",
    "sinal do 'rim' no tumor de ovário",
    "cisto hemorrágico"
  ],
  sistema_nervoso: [
    "lesão expansiva",
    "edema vasogênico",
    "edema citotóxico",
    "meninge realçada",
    "infarto agudo",
    "infarto subagudo",
    "infarto crônico",
    "gliose",
    "placas desmielinizantes",
    "microporos",
    "hemorragia subaracnoide",
    "hematoma subdural",
    "hematoma epidural",
    "hidrocefalia comunicante",
    "hidrocefalia não comunicante",
    "malformação arteriovenosa (MAV)",
    "aneurisma cerebral",
    "sinal da artéria hiperdensa",
    "desvio da linha média",
    "hernização uncal",
    "atrofia cortical",
    "sinal da dupla coroa",
    "sinal do ponto",
    "sinal da insula",
    "encefalomalácia",
    "leucoencefalopatia",
    "cavidade porencefálica",
    "cisto aracnoide",
    "tumores gliais",
    "metástase cerebral",
    "angioma cavernoso",
    "dissecção arterial cervical"
  ],
  musculoesqueletico: [
    "derrame articular",
    "condromalácia",
    "lesão de LCA",
    "lesão de LCP",
    "lesão do menisco medial",
    "lesão do menisco lateral",
    "lesão em alça de balde",
    "tenossinovite",
    "osteíte",
    "osteomielite",
    "fratura por estresse",
    "fratura patológica",
    "edema ósseo",
    "ruptura do manguito rotador",
    "tendinopatia",
    "bursite",
    "artrose",
    "espondilolistese",
    "hérnia discal",
    "protrusão discal",
    "extrusão discal",
    "degeneração mucoide",
    "cisto de Baker",
    "reação periosteal",
    "córtex insuflado",
    "padrão permeativo",
    "padrão geográfico",
    "triângulo de Codman",
    "esclerose subcondral",
    "osteófitos",
    "sinovite",
    "impingement femoroacetabular",
    "lesão labral",
    "atrofia muscular",
    "necrose avascular"
  ],
  vascular: [
    "estenose",
    "estenose crítica",
    "estenose suboclusiva",
    "trombose venosa profunda (TVP)",
    "trombose arterial",
    "dissecção aórtica",
    "aneurisma sacular",
    "aneurisma fusiforme",
    "oclusão",
    "pseudoaneurisma",
    "fístula arteriovenosa",
    "placa aterosclerótica",
    "placa calcificada",
    "varizes",
    "sinal de flow void",
    "fluxo turbulento",
    "onda trifásica",
    "onda bifásica",
    "onda monofásica",
    "calcificação parietal",
    "estenose carotídea",
    "vasoespasmo",
    "insuficiência venosa",
    "trombo mural",
    "dilatação aneurismática"
  ],
  procedimentos: [
    "punção aspirativa por agulha fina (PAAF)",
    "biópsia por agulha grossa (core biopsy)",
    "drenagem percutânea",
    "radioablação",
    "crioablação",
    "injeção intra-articular",
    "embolização",
    "quimioembolização (TACE)",
    "vertebroplastia",
    "cifoplastia",
    "nefrostomia",
    "angiografia",
    "cateterismo",
    "marcação pré-cirúrgica",
    "fluoroscopia",
    "artrografia",
    "colangiografia",
    "tomografia computadorizada de dupla energia (DECT)"
  ],
  patologias_gerais: [
    "carcinoma",
    "adenocarcinoma",
    "carcinoma de células escamosas",
    "hemangioma",
    "linfoma",
    "abscesso",
    "hematoma",
    "necrose",
    "necrose gordurosa",
    "cisto simples",
    "cisto complexo",
    "metástase",
    "fibrose",
    "inflamação",
    "granuloma",
    "lipoma",
    "teratoma",
    "sarcoma",
    "calcificação distrófica",
    "processo inflamatório crônico",
    "doença de Crohn",
    "colite ulcerativa",
    "tuberculose",
    "candidíase",
    "esclerose múltipla",
    "encefalite",
    "meningite",
    "artrite reumatoide",
    "lúpus eritematoso sistêmico",
    "amiloidose"
  ],
  
  // === PATOLOGIAS NEURORRADIOLÓGICAS ===
  patologias_neuro: [
    // VASCULARES
    "avc", "avci", "avch",
    "isquêmico", "isquêmica", "isquêmicos", "isquêmicas",
    "hemorrágico", "hemorrágica", "hemorrágicos", "hemorrágicas",
    "hematoma", "hematomas",
    "hemorragia", "hemorragias",
    "subdural", "epidural", "subaracnóidea", "subaracnoide",
    "intraparenquimatoso", "intraparenquimatosa",
    "aneurisma", "aneurismas",
    "malformação", "malformações",
    "arteriovenosa", "arteriovenosas",
    "cavernoma", "cavernomas",
    "angioma", "angiomas",
    "telangiectasia", "telangiectasias",
    "fístula", "fístulas",
    "trombose", "tromboses",
    "venosa", "venoso", "venosas", "venosos",
    "aterosclerose", "aterosclerótico", "aterosclerótica",
    "vasculite", "vasculites",
    "moyamoya",
    "dissecção", "dissecções",
    "vasospasmo",
    
    // TUMORES
    "glioma", "gliomas",
    "glioblastoma", "glioblastomas",
    "astrocitoma", "astrocitomas",
    "oligodendroglioma", "oligodendrogliomas",
    "ependimoma", "ependimomas",
    "meduloblastoma", "meduloblastomas",
    "meningioma", "meningiomas",
    "schwannoma", "schwannomas",
    "neurinoma", "neurinomas",
    "neurofibroma", "neurofibromas",
    "craniofaringioma", "craniofaringiomas",
    "adenoma", "adenomas",
    "hipofisário", "hipofisária", "hipofisários", "hipofisárias",
    "prolactinoma", "prolactinomas",
    "linfoma", "linfomas",
    "pinealoma", "pinealomas",
    "meduloepitelioma",
    "teratoma", "teratomas",
    "germinoma", "germinomas",
    "hemangioblastoma", "hemangioblastomas",
    
    // DESMIELINIZANTES
    "esclerose", "escleroses",
    "múltipla",
    "desmielinização", "desmielinizante", "desmielinizantes",
    "leucoencefalopatia", "leucoencefalopatias",
    "neuromielite",
    "óptica",
    "encefalomielite",
    "adrenoleucodistrofia",
    "leucodistrofia", "leucodistrofias",
    
    // INFECCIOSAS
    "encefalite", "encefalites",
    "meningite", "meningites",
    "meningoencefalite", "meningoencefalites",
    "cerebrite",
    "empiema", "empiemas",
    "toxoplasmose",
    "neurocisticercose", "cisticercose",
    "tuberculose", "tuberculoma", "tuberculomas",
    "neurotoxoplasmose",
    "herpes", "herpética", "herpético",
    "citomegalovírus",
    "leucoencefalopatia multifocal progressiva", "lemp",
    "prion", "creutzfeldt-jakob",
    
    // DEGENERATIVAS
    "alzheimer",
    "parkinson",
    "demência", "demências",
    "atrofia", "atrofias",
    "cortical", "corticais",
    "cerebelar",
    "hidrocefalia", "hidrocéfalo",
    "leucoaraiose",
    "gliose", "glioses",
    "encefalomalácia",
    "wallerian", "walleriana",
    "huntington",
    
    // CONGÊNITAS/MALFORMAÇÕES
    "malformação", "malformações",
    "arnold-chiari", "chiari",
    "dandy-walker",
    "agenesia", "agenesias",
    "hipoplasia", "hipoplasias",
    "holoprosencefalia",
    "lisencefalia",
    "paquigiria",
    "polimicrogiria",
    "heterotopia", "heterotopias",
    "esquizencefalia",
    "displasia", "displasias",
    "mielocele", "mielomeningocele",
    "lipoma", "lipomas",
    "dermoide", "dermoides",
    "epidermoide", "epidermoides",
    
    // COLUNA/MEDULA
    "hérnia", "hérnias",
    "discal", "discais",
    "protrusão", "protrusões",
    "extrusão", "extrusões",
    "espondilose",
    "espondilite",
    "espondilolistese",
    "espondilólise",
    "mielopatia", "mielopatias",
    "siringomielia", "siringomielias",
    "compressão", "compressões",
    "medular", "medulares",
    "radiculopatia", "radiculopatias",
    "estenose", "estenoses",
    "foraminal", "foraminais",
    
    // HIDROCEFALIA
    "ventriculomegalia",
    "hidrocefalia",
    "hidrocéfalo",
    "comunicante",
    "obstrutivo", "obstrutiva",
    "pressão normal",
    "derivação", "derivações"
  ],
  
  // === PATOLOGIAS DE CABEÇA E PESCOÇO ===
  patologias_cabeca_pescoco: [
    // ÓRBITA E GLOBO OCULAR
    "pseudotumor", "orbitário", "orbitária",
    "celulite", "pré-septal", "septal",
    "oftalmopatia", "graves",
    "dacrioadenite", "dacriocistite",
    "hemangioma capilar", "hemangioma cavernoso",
    "varizes", "linfangioma",
    "retinoblastoma", "melanoma", "uveal",
    "neurite", "óptica", "óptico",
    "proptose", "enoftalmia", "exoftalmia",
    
    // SEIOS PARANASAIS E CAVIDADE NASAL
    "sinusite", "rinossinusite",
    "maxilar", "etmoidal", "esfenoidal", "frontal",
    "pansinusite",
    "fúngica", "fúngico",
    "pólipo", "pólipos", "polipose", "polipoides",
    "papiloma", "invertido",
    "estesioneuroblastoma",
    "desvio", "septal", "perfuração",
    "granulomatose", "wegener",
    "aspergilose",
    
    // OSSO TEMPORAL E ORELHA
    "colesteatoma", "colesteatomas",
    "otite", "média", "crônica",
    "otomastoidite", "mastoidite",
    "timpanoesclerose",
    "otosclerose",
    "labirintite",
    "vestibular", "vestibulares",
    "neuroma", "acústico",
    "ménière",
    "paraganglioma", "paragangliomas",
    "glomus", "jugular", "timpânico",
    "atresia", "auditivo",
    "mondini",
    "aqueduto", "alargado",
    
    // GLÂNDULAS SALIVARES
    "sialadenite", "sialolitíase",
    "parotidite", "submandibulite",
    "pleomórfico", "pleomórfica",
    "warthin",
    "oncocitoma",
    "linfoepitelial",
    "mucoepidermoide",
    "acinares",
    "sialose",
    "sjögren",
    "rânula",
    
    // FARINGE E CAVIDADE ORAL
    "nasofaringe", "orofaringe", "hipofaringe",
    "assoalho", "bucal",
    "peritonsilar", "retrofaríngeo", "parafaríngeo",
    "tornwaldt",
    "angioedema",
    "tonsilite", "faringite",
    "mononucleose",
    
    // LARINGE
    "vocal", "vocais",
    "papilomatose",
    "laringocele",
    "glótico", "glótica",
    "supraglótico", "supraglótica",
    "subglótico", "subglótica",
    "transglótico", "transglótica",
    "reinke",
    "laringite",
    
    // TIREOIDE E PARATIREOIDES
    "tireoidiano", "tireoidiana",
    "bócio", "multinodular",
    "coloide", "coloides",
    "folicular", "foliculares",
    "hashimoto",
    "papilífero", "papilífera",
    "medular", "medulares",
    "anaplásico", "anaplásica",
    "paratireoide", "paratireoides",
    
    // ESPAÇOS CERVICAIS PROFUNDOS
    "branquial", "branquiais",
    "tireoglosso",
    "higroma",
    "carotídea", "carotídeo", "carotídeas",
    "corpo carotídeo",
    
    // LINFONODOS CERVICAIS
    "linfadenopatia", "reativa",
    "linfadenite",
    "tuberculose ganglionar",
    "linfonodal", "linfonodais",
    "hodgkin",
    "extracapsular",
    "conglomerado"
  ],
  
  // === PATOLOGIAS DE TÓRAX E MEDIASTINO ===
  patologias_torax_mediastino: [
    // INFECCIOSAS PULMONARES
    "pneumonia", "pneumônico", "pneumônica", "pneumônicos",
    "bacteriana", "bacteriano", "bacterianas",
    "viral", "virais",
    "aspirativa", "aspirativo",
    "lipídica", "lipídico",
    "tuberculosa", "tuberculoso",
    "aspergiloma", "aspergilomas",
    "pneumocistose", "pneumocystis",
    "abscesso", "abscessos",
    "empiema", "empiemas",
    "broncopneumonia", "broncopneumônico", "broncopneumônica",
    "nocardiose",
    "micobacteriose", "micobacteriana", "micobacteriano",
    "histoplasmose", "histoplasma",
    "paracoccidioidomicose", "paracoccidiodomicose",
    "criptococose", "criptocócica", "criptocócico",
    
    // INTERSTICIAIS
    "pneumonite", "pneumonites",
    "sarcoidose", "sarcoidótico", "sarcoidótica",
    "pneumoconiose", "pneumoconioses",
    "silicose", "silicótico", "silicótica",
    "asbestose", "asbestótico", "asbestótica",
    "antracose", "antracótico", "antracótica",
    "fibrocística",
    "alveolite", "alveolites",
    "proteinose",
    "hemossiderose", "hemossiderótico", "hemossiderótica",
    "pós-covid", "pós-COVID",
    "DAD", "dano alveolar difuso",
    "linfangite", "linfangítica", "linfangítico",
    "carcinomatosa", "carcinomatoso",
    "hipersensibilidade",
    "bronquiolite", "bronquiolites",
    "obliterante", "obliterativa", "obliterativo",
    "constritiva", "constritivo",
    
    // NEOPLASIAS PULMONARES
    "broncogênico", "broncogênica",
    "células pequenas",
    "células grandes",
    "escamoso", "escamosa",
    "carcinoide", "carcinoides",
    "hamartoma", "hamartomas",
    "pancoast",
    "linfangioleiomiomatose", "LAM",
    "histiocitose", "histiocitoses",
    "langerhans",
    "mesotelioma", "mesoteliomas",
    "timoma", "timomas", "tímico", "tímica",
    "metastático", "metastática",
    
    // VASCULARES PULMONARES
    "tromboembolismo", "tromboembólico", "tromboembólica",
    "TEP",
    "êmbolo", "êmbolos",
    "embolismo", "embólico", "embólica",
    "infartado", "infartada",
    "hipertensiva", "hipertensivo",
    "edematoso", "edematosa",
    "cardiogênico", "cardiogênica",
    "SARA", "SDRA",
    "hemorrágica", "hemorrágico",
    "vasculítica", "vasculítico",
    "MAVP",
    "sequestro", "sequestração",
    "hipoplásico", "hipoplásica",
    
    // PLEURA
    "pleurite", "pleurítico", "pleurítica",
    "loculado", "loculada", "loculados",
    "hemotórax",
    "quilotórax",
    "hipertensivo", "hipertensiva",
    "hidropneumotórax",
    "fibrotórax",
    
    // MEDIASTINO
    "carcinoma tímico",
    "hiperplasia tímica",
    "cisto tímico",
    "germinativo", "germinativa",
    "seminoma", "seminomas",
    "mergulhante", "retroesternal",
    "cisto broncogênico",
    "duplicação",
    "lipomatose",
    "mediastinite", "mediastínico", "mediastínica",
    "fibrosante",
    "neuroblastoma", "neuroblastomas",
    "ganglioneuroma", "ganglioneuromas",
    "neurogênico", "neurogênica",
    "acalasia",
    "hiatal", "hiato",
    "zenker",
    
    // TERMOS DESCRITIVOS
    "subsólido", "subsólida", "subsólidos", "subsólidas",
    "subpleural", "subpleurais",
    "peribrônquico", "peribrônquica", "peribrônquicos",
    "peribronquiovascular",
    "centrilobular", "centrilobulares",
    "perilobular", "perilobulares",
    "interlobular", "interlobulares",
    "paraseptal", "paraseptais",
    "perifissural",
    "perihilar", "justa-hilar",
    "paratraqueal", "paratraqueais",
    "aortopulmonar",
    "paravertebral", "paravertebrais",
    "retrocardíaco", "retrocardíaca",
    "retrosternal",
    "prevascular",
    "infracarinal",
    "hilomegalia",
    "cardiomegalia",
    "hiperinsuflação", "hiperinsuflado", "hiperinsuflada",
    "hipoventilação", "hipoventilado", "hipoventilada",
    
    // ANATOMIA COMPLEMENTAR
    "carina", "carinal",
    "lobos", "lobar", "lobares",
    "bronquíolo", "bronquiolar", "bronquiolares",
    "alvéolo", "alveolares",
    "interstício",
    "ápice", "apical", "apicais",
    "basal", "basais",
    "cissura", "cissuras", "fissurite",
    "língula", "lingular",
    "costofrênico", "costofrênicos",
    "cardiofrênico", "cardiofrênicos",
    "timo",
    "recesso",
    "azigoesofágico",
    "ázigos"
  ],
  
  // === PATOLOGIAS ABDOMINAIS ===
  patologias_abdome: [
    // FÍGADO E VIAS BILIARES
    "hepatocarcinoma", "CHC", "carcinoma hepatocelular",
    "colangiocarcinoma", "colangiocarcinomas",
    "colangítico", "colangítica",
    "metástase hepática", "metástases hepáticas",
    "hepatite", "hepatítico", "hepatítica",
    "cirrose", "cirrótico", "cirrótica",
    "fibrose hepática", "fibrosante",
    "colangite", "esclerosante",
    "abscesso hepático", "piogênico",
    "amebiano", "amebiana",
    "equinococose", "hidatidose", "hidático", "hidática",
    "esquistossomótico", "esquistossomótica",
    "budd-chiari", "síndrome de budd-chiari",
    "doença veno-oclusiva", "veno-oclusiva",
    "congestivo", "congestiva",
    "hipertensão portal", "portais",
    "varizes esofágicas", "varicoso", "varicosa",
    "shunt portossistêmico", "esplenorrenal",
    "caroli", "doença de caroli",
    "fibropolicístico", "fibropolicística",
    "hamartoma biliar", "complexos de von meyenburg",
    "peribiliar", "peribiliares",
    "regenerativo", "regenerativa",
    "periportal", "periportais",
    
    // VESÍCULA BILIAR
    "colecistite crônica", "colecistite alitiásica",
    "alitiásica", "alitiásico",
    "vesícula em porcelana", "escleroatrófica",
    "adenomiomatose", "adenomiomatosa",
    "pólipo vesicular", "pólipos vesiculares",
    "barro biliar", "lama biliar",
    "microlitíase", "microcalculose",
    "carcinoma vesicular",
    "fístula colecistoentérica", "colecistoentérica",
    "íleo biliar",
    "empiema vesicular",
    "hidrops vesicular", "hidrops",
    "sinal de murphy", "murphy",
    
    // PÂNCREAS
    "adenocarcinoma pancreático",
    "tumor neuroendócrino pancreático", "TNE",
    "insulinoma", "insulinomas",
    "gastrinoma", "gastrinomas",
    "glucagonoma", "glucagonomas",
    "vipoma", "somatostatinoma",
    "cistoadenoma seroso", "cistoadenoma mucinoso",
    "mucinoso", "mucinosa", "mucinosos",
    "IPMN", "neoplasia papilar mucinosa",
    "ramo principal", "ramo secundário",
    "tumor sólido pseudopapilar", "frantz",
    "pancreatoblastoma",
    "pancreas divisum", "divisum",
    "pâncreas anular", "anular",
    "wirsung", "ducto de wirsung",
    "santorini", "ducto de santorini",
    "parênquima pancreático",
    "atrófico", "atrófica", "atróficos",
    "lipomatose pancreática",
    "calcificações pancreáticas",
    "necrosante", "necrotizante",
    "walled-off", "coleção organizada",
    "coleção peripancreática", "peripancreático",
    "necrose gordurosa", "saponificação",
    
    // BAÇO
    "infarto esplênico", "infartos esplênicos",
    "esplenose", "esplenoses",
    "baço acessório", "esplenúnculo",
    "rotura esplênica", "laceração esplênica",
    "hematoma esplênico", "subcapsular",
    "linfoma esplênico",
    "sarcoidose esplênica",
    "tuberculose esplênica",
    "granulomatoso", "granulomatosa",
    "angiosarcoma esplênico",
    "hemangioma esplênico",
    "hamartoma esplênico",
    "linfangioma esplênico",
    "cisto epidermóide",
    "asplenia", "asplênico",
    "poliesplenia", "poliesplenismo",
    "wandering spleen", "baço errante",
    
    // RINS E SISTEMA URINÁRIO
    "carcinoma de células renais", "CCR",
    "carcinoma cromófobo", "cromófobo",
    "carcinoma papilífero renal",
    "oncocitoma renal", "oncocitoma",
    "angiomiolipoma", "AML", "angiomiolipomas",
    "lipoma renal",
    "linfoma renal",
    "metástase renal",
    "urotelial", "uroteliais",
    "carcinoma urotelial",
    "tuberculose renal",
    "xantogranulomatosa", "xantogranulomatoso",
    "pionefrose", "pionefroses",
    "abscesso renal", "abscessos renais",
    "nefrosclerose", "nefrosclerótico",
    "nefropatia", "nefropático",
    "glomeruloesclerose",
    "nefrite", "nefrítico", "nefrítica",
    "síndrome nefrótico", "nefrótico", "nefrótica",
    "insuficiência renal",
    "atrofia renal", "rim atrófico",
    "duplicidade piélica", "duplicação piélica",
    "duplicação ureteral",
    "ectopia renal", "ectópico",
    "rim em ferradura", "fusão renal",
    "agenesia renal",
    "hipoplasia renal", "hipoplásico",
    "infarto renal",
    "necrose cortical",
    "trombose de veia renal",
    "estenose de artéria renal",
    "ureterolitíase", "ureterolítico",
    "ureterocele", "ureteroceles",
    "megaureter", "megaureteres",
    "refluxo vesicoureteral", "vesicoureteral",
    
    // GLÂNDULAS ADRENAIS
    "adenoma adrenal", "adenomas adrenais",
    "incidentaloma", "incidentalomas",
    "feocromocitoma", "feocromocitomas",
    "neuroblastoma adrenal",
    "mielolipoma", "mielolipomas",
    "carcinoma adrenal",
    "hiperplasia adrenal",
    "metástase adrenal",
    "tuberculose adrenal",
    "hemorragia adrenal",
    "hematoma adrenal",
    "cisto adrenal",
    "addison", "doença de addison",
    "cushing", "síndrome de cushing",
    "conn", "síndrome de conn",
    
    // TRATO GASTROINTESTINAL
    "esofagite", "esofágico", "esofágica",
    "barret", "esôfago de barret",
    "estenose esofágica",
    "acalasia esofágica",
    "carcinoma esofágico",
    "leiomioma esofágico",
    "hérnia hiatal",
    "megaesôfago", "chagásico",
    "gastropatia", "gastropatias",
    "gastrite", "gastrítico", "gastrítica",
    "úlcera gástrica", "úlcera péptica",
    "adenocarcinoma gástrico",
    "GIST", "tumor estromal",
    "leiomioma gástrico",
    "linite plástica",
    "linfoma gástrico",
    "pólipo gástrico", "pólipos gástricos",
    "bezoar", "bezoares",
    "volvo gástrico",
    "enterite", "enterítico",
    "ileíte", "ileítico",
    "jejunite", "duodenite",
    "crohn", "doença de crohn",
    "celíaca", "celíaco", "doença celíaca",
    "linfoma intestinal",
    "tumor carcinoide",
    "carcinoma colorretal",
    "adenoma colônico", "adenomas colônicos",
    "polipose", "poliposas",
    "síndrome de lynch", "lynch",
    "diverticulose", "diverticular",
    "megacólon", "megacólons",
    "volvo sigmoide", "volvo cecal",
    "isquemia mesentérica",
    "infarto intestinal",
    "pneumatose intestinal", "pneumatose",
    "enterocolite", "enterocolítica",
    
    // PERITÔNIO E PAREDE ABDOMINAL
    "carcinomatose peritoneal", "carcinomatose",
    "pseudomixoma", "pseudomixoma peritoneal",
    "mesotelioma peritoneal",
    "tuberculose peritoneal",
    "peritonite", "peritonítico", "peritonítica",
    "hemoperitoneal", "hemoperitônio",
    "hérnia inguinal", "inguinal",
    "hérnia umbilical", "umbilical",
    "hérnia incisional", "incisional",
    "hérnia de spiegel", "spiegel",
    "hérnia femoral",
    "eventração", "eventrações",
    "diastase de retos", "diástase",
    "hematoma de parede",
    "desmóide", "desmoides",
    "fibromatose", "fibromatosa",
    "lipoma de parede",
    "endometriose de parede",
    "cisto de úraco", "úraco",
    "onfalocele", "gastrosquise"
  ],
  
  rads_scores: [
    "BI-RADS 0", "BI-RADS 1", "BI-RADS 2", "BI-RADS 3", "BI-RADS 4A", "BI-RADS 4B", "BI-RADS 4C", "BI-RADS 5", "BI-RADS 6",
    "TI-RADS 1", "TI-RADS 2", "TI-RADS 3", "TI-RADS 4", "TI-RADS 5",
    "PI-RADS 1", "PI-RADS 2", "PI-RADS 3", "PI-RADS 4", "PI-RADS 5",
    "LI-RADS 1", "LI-RADS 2", "LI-RADS 3", "LI-RADS 4", "LI-RADS 5", "LI-RADS TIV", "LI-RADS M",
    "O-RADS 1", "O-RADS 2", "O-RADS 3", "O-RADS 4", "O-RADS 5",
    "Lung-RADS 1", "Lung-RADS 2", "Lung-RADS 3", "Lung-RADS 4A", "Lung-RADS 4B", "Lung-RADS 4X",
    "CAD-RADS 0", "CAD-RADS 1", "CAD-RADS 2", "CAD-RADS 3", "CAD-RADS 4", "CAD-RADS 5",
    "C-RADS", "NI-RADS", "VIR-RADS"
  ],
  termos_quantitativos: [
    "aumentado",
    "reduzido",
    "espessado",
    "afinamento",
    "assimétrico",
    "simétrico",
    "volumoso",
    "dimensões preservadas",
    "> 1 cm",
    "< 1 cm",
    "> 10 mm",
    "< 10 mm",
    "medindo",
    "centimetrado",
    "milimetrado",
    "discreto",
    "moderado",
    "acentuado",
    "extenso",
    "focal",
    "difuso",
    "global",
    "parcial",
    "significativo",
    "mínimo",
    "leve",
    "acima do percentil 95"
  ],
  termos_descricao: [
    "heterogêneo",
    "homogêneo",
    "regular",
    "irregular",
    "bem delimitado",
    "mal delimitado",
    "lobulado",
    "espiculado",
    "indefinido",
    "circunscrito",
    "serpiginoso",
    "marginal",
    "hipoecogênico",
    "hiperecogênico",
    "hiperdenso",
    "hipodenso",
    "cístico",
    "sólido",
    "complexo",
    "multi-septado",
    "septado",
    "liso",
    "rugoso",
    "pedunculado",
    "séssil",
    "microlobulado",
    "macrolobulado",
    "polipoide",
    "móvel",
    "fixo",
    "redondo",
    "ovalado",
    "fusiforme",
    "amórfico",
    "linear"
  ],
  portugues_laudo: [
    // === VERBOS COMUNS EM LAUDOS ===
    "realizado", "realizada", "realizados", "realizadas",
    "apresenta", "apresentam", "apresentando",
    "observa", "observado", "observada", "observados", "observadas", "observando",
    "demonstra", "demonstrando", "demonstrado", "demonstrada",
    "evidencia", "evidenciado", "evidenciada", "evidenciando", "evidências",
    "mostra", "mostrando", "mostrado", "mostrada",
    "sugere", "sugerindo", "sugestivo", "sugestiva",
    "pode", "podem", "poderá", "poderão", "podendo",
    "indica", "indicando", "indicado", "indicada",
    "permite", "permitindo", "permitido",
    "exclui", "excluir", "excluído", "excluída",
    "confirma", "confirmado", "confirmada", "confirmando",
    "caracteriza", "caracterizado", "caracterizada",
    "mede", "medindo", "medido", "medida",
    "localiza", "localizado", "localizada",
    "apresentar", "observar", "demonstrar", "evidenciar",
    
    // === SUBSTANTIVOS COMUNS ===
    "exame", "exames", "estudo", "estudos",
    "aspecto", "aspectos", "ausência", "presença",
    "região", "regiões", "área", "áreas",
    "dimensões", "dimensão", "limites", "limite",
    "contornos", "contorno", "margens", "margem",
    "planos", "plano", "cortes", "corte",
    "incidências", "incidência", "projeções", "projeção",
    "achados", "achado", "alterações", "alteração",
    "sinais", "sinal", "imagens", "imagem",
    "lesão", "lesões", "intensidade", "intensidades",
    "avaliação", "análise", "comparação",
    "contraste", "controle", "seguimento",
    "técnica", "método", "protocolo",
    "estruturas", "estrutura", "órgãos", "órgão",
    "sistema", "sistemas", "aparelho",
    "informações", "informação", "dados", "dado",
    "conclusão", "impressão", "opinião",
    "hipótese", "diagnóstico", "diagnósticos",
    "paciente", "examinado", "examinada",
    "ano", "anos", "mês", "meses", "dia", "dias",
    "lado", "lados", "porção", "porções",
    "terço", "terços", "metade",
    "densidade", "densidades",
    "tamanho", "forma", "posição",
    
    // === ADJETIVOS COMUNS ===
    "normal", "normais", "habitual", "habituais",
    "preservado", "preservada", "preservados", "preservadas",
    "característica", "características", "característico", "característicos",
    "compatível", "compatíveis", "sugestivo", "sugestiva",
    "típico", "típica", "típicos", "típicas",
    "atípico", "atípica", "atípicos", "atípicas",
    "usual", "incomum", "frequente", "raro", "rara",
    "bilateral", "bilaterais", "unilateral", "unilaterais",
    "anterior", "posterior", "superior", "inferior",
    "medial", "lateral", "proximal", "distal",
    "direito", "direita", "esquerdo", "esquerda",
    "pequeno", "pequena", "pequenos", "pequenas",
    "grande", "grandes", "médio", "média", "médios", "médias",
    "alto", "alta", "altos", "altas",
    "baixo", "baixa", "baixos", "baixas",
    "bom", "boa", "bons", "boas",
    "mau", "má", "maus", "más",
    "livre", "livres", "restrito", "restrita",
    "adequado", "adequada", "inadequado", "inadequada",
    "presente", "presentes", "ausente", "ausentes",
    "novo", "nova", "novos", "novas",
    "antigo", "antiga", "antigos", "antigas",
    "recente", "recentes", "prévio", "prévia",
    "adicional", "adicionais", "complementar", "complementares",
    "principal", "principais", "secundário", "secundária",
    "único", "única", "únicos", "únicas",
    "múltiplo", "múltipla", "múltiplos", "múltiplas",
    "denso", "densa", "densos", "densas",
    "espesso", "espessa", "fino", "fina",
    "profundo", "profunda", "superficial",
    "central", "periférico", "periférica",
    
    // === CONECTIVOS E PREPOSIÇÕES ===
    "que", "qual", "quais", "como", "onde",
    "com", "sem", "para", "por", "entre",
    "sobre", "sob", "após", "antes",
    "durante", "através", "mediante",
    "conforme", "segundo", "devido",
    "além", "inclusive", "exceto",
    
    // === ADVÉRBIOS ===
    "não", "sim", "bem", "mal",
    "mais", "menos", "muito", "pouco",
    "apenas", "somente", "principalmente",
    "parcialmente", "completamente", "totalmente",
    "provavelmente", "possivelmente", "certamente",
    "aparentemente", "relativamente", "aproximadamente",
    "tipicamente", "usualmente", "normalmente",
    "eventualmente", "ocasionalmente", "raramente",
    
    // === ARTIGOS E PRONOMES ===
    "este", "esta", "estes", "estas",
    "esse", "essa", "esses", "essas",
    "aquele", "aquela", "aqueles", "aquelas",
    "seu", "sua", "seus", "suas",
    "mesmo", "mesma", "mesmos", "mesmas",
    "outro", "outra", "outros", "outras",
    "todo", "toda", "todos", "todas",
    "cada", "alguns", "algumas", "nenhum", "nenhuma",
    
    // === NÚMEROS ORDINAIS ===
    "primeiro", "primeira", "segundo", "segunda",
    "terceiro", "terceira", "quarto", "quarta",
    
    // === TERMOS TÉCNICOS GERAIS ===
    "digital", "analógico", "computadorizado",
    "intravenoso", "intravenosa", "oral",
    "mamográfico", "mamográfica", "mamografia",
    "ultrassonografia", "ultrassonográfico", "ultrassonográfica",
    "tomográfico", "tomográfica",
    "radiográfico", "radiográfica", "radiografia",
    "ocultar", "oculto", "oculta", "obscurecer",
    "trazer", "traz", "trazendo",
    "indicar", "indicando",
    "rastreamento", "screening",
    "categoria", "categorias", "classificação",
    
    // === TERMOS ANATÔMICOS DE USO GERAL ===
    "mama", "mamas", "axilar", "axilares",
    "mamário", "mamária", "tecido",
    "glandular", "adiposo", "fibroglandular",
    "nódulo", "nódulos", "calcificação", "calcificações",
    "benigno", "benigna", "benignas", "benignos",
    "maligno", "maligna", "malignas", "malignos",
    "patológico", "patológica",
    "parênquima", "estroma",
    "esparsas", "dispersas", "agrupadas"
  ],
  
  // === CATEGORIA: TERMOS EXTRAÍDOS DE TEMPLATES E FRASES DO BANCO SUPABASE ===
  termos_templates_supabase: [
    // === ANATOMIA ABDOMINAL ===
    "fígado", "hepático", "hepática", "hepáticos", "hepáticas",
    "parenquimatosa", "parenquimatoso",
    "vesícula", "vesicular", "biliar", "biliares",
    "colédoco", "hepatocolédoco", "cístico",
    "pâncreas", "pancreático", "pancreática",
    "ducto", "ductos", "ductais", "ductal",
    "baço", "esplênico", "esplênica",
    "adrenais", "adrenal",
    "rins", "rim", "renal", "renais",
    "bexiga", "vesical",
    "intestino", "intestinal", "intestinais",
    "alças", "delgadas", "delgado",
    "cólon", "cólica", "cólico",
    "reto", "retal",
    "duodeno", "duodenal",
    "estômago", "gástrico", "gástrica",
    "aorta", "aórtico", "aórtica", "aórticos",
    "veia", "veias", "venoso", "venosa", "venosos", "venosas",
    "cava", "porta", "portais", "portal",
    "artéria", "artérias", "arterial", "arteriais",
    "mesentérica", "mesentérico",
    "ilíaca", "ilíaco", "ilíacas",
    "retroperitoneal", "retroperitoneais", "retroperitônio",
    "peritônio", "peritoneal",
    "cavidade", "abdominal", "abdominais",
    
    // === ANATOMIA TORÁCICA ===
    "pulmão", "pulmões", "pulmonar", "pulmonares",
    "pleura", "pleural", "pleurais",
    "mediastino", "mediastinal", "mediastinais",
    "traqueia", "traqueal",
    "brônquios", "brônquio", "brônquico", "brônquica",
    "costais", "costal", "arcos",
    "diafragma", "diafragmático", "diafragmática",
    "cardíaco", "cardíaca", "cardíacos",
    "pericárdio", "pericárdico",
    
    // === ANATOMIA NEUROLÓGICA ===
    "cérebro", "cerebral", "cerebrais",
    "cerebelo", "cerebelar", "cerebelares",
    "hemisférios", "hemisfério",
    "ventrículos", "ventrículo", "ventricular",
    "substância", "substâncias",
    "cinzenta", "branca",
    "córtex", "cortical", "corticais", "subcortical",
    "sulcos", "sulcação",
    "giros", "giro",
    "meninges", "meníngeo", "meníngea",
    "dural", "durais",
    "medula", "medular", "medulares",
    "espinhal", "raquiano", "raquidiano",
    "nervos", "nervo", "nervoso", "nervosa",
    "tronco", "encefálico",
    "hipófise", "hipofisária", "hipofisário",
    "selar", "sela", "túrcica",
    "órbitas", "orbitário", "orbitária",
    "globos", "oculares", "ocular",
    
    // === ANATOMIA MUSCULOESQUELÉTICA ===
    "vértebras", "vértebra", "vertebral", "vertebrais",
    "discos", "disco", "discal", "discais", "intervertebrais",
    "coluna", "cervical", "torácica", "lombar", "sacral",
    "sacro", "sacroilíacas", "coccígeas", "coccígeos",
    "articulações", "articular", "articulares",
    "facetárias", "interapofisárias",
    "ligamentos", "ligamento", "ligamentares",
    "tendões", "tendão", "tendinoso", "tendinosa",
    "músculos", "músculo", "muscular", "musculares",
    "osso", "ossos", "ósseo", "óssea", "ósseas",
    "meniscos", "menisco",
    "cartilagem", "cartilaginoso", "cartilaginosa",
    "labrum", "labral",
    "superfícies", "superfície",
    "epífises", "epífise", "epifisário",
    
    // === ANATOMIA PELVE ===
    "útero", "uterino", "uterina", "uterinos",
    "ovários", "ovário", "ovariano", "ovariana",
    "anexos", "anexiais", "anexial",
    "endométrio", "endometrial",
    "miométrio", "miometrial",
    "cérvix",
    "vagina", "vaginal",
    "próstata", "prostático", "prostática", "prostáticos",
    "seminais", "seminal",
    "testículos", "testículo", "testicular",
    "epidídimo", "epidídimos",
    "funículo", "espermático",
    
    // === ANATOMIA MAMA ===
    "mama", "mamas", "mamário", "mamária", "mamários", "mamárias",
    "fibroglandular", "glandular",
    "retroglandular", "subglandular",
    "axilar", "axilares", "axila",
    "areolopapilares", "areolar",
    "peitoral", "retropeitoral",
    
    // === ANATOMIA VASCULAR ===
    "carótida", "carótidas", "carotídeo", "carotídeos", "carotídeas",
    "subclávia", "subclávias",
    "jugulares", "jugular",
    "braquiocefálico",
    "vertebrobasilar",
    "femorais", "femoral",
    "poplítea", "poplíteo",
    "tibiais", "tibial",
    "fibular", "fibulares",
    "pediosa",
    
    // === DESCRITORES MORFOLÓGICOS ===
    "calibre", "calibres",
    "contornos", "bordos", "bordas", "margens",
    "regulares", "irregulares",
    "lisos", "lisas", "serrilhados",
    "finos", "finas",
    "espessura", "espessamento",
    "morfologia", "configuração",
    "trajeto", "percurso",
    "topografia", "tópico", "tópicos", "tópica",
    "posicionado", "posicionados", "normoposicionado", "normoposicionados",
    
    // === DESCRITORES DE SINAL/DENSIDADE ===
    "ecotextura", "ecogenicidade",
    "hiperecogênica", "hiperecogênico", "hiperecogênicas",
    "hipoecogênica", "hipoecogênico", "hipoecogênicas",
    "anecoico", "anecóico", "anecoica",
    "isoecogênico", "isoecogênica",
    "hipointenso", "hiperintenso", "isointenso",
    "hipodenso", "hiperdenso", "isodenso",
    "atenuação",
    
    // === DESCRITORES DE ESTADO/CONDIÇÃO ===
    "íntegro", "íntegra", "íntegros", "íntegras",
    "pérvio", "pérvia", "pérvios", "pérvias",
    "patente", "patentes",
    "normodistendido", "normodistendida",
    "distendido", "distendida", "distensão", "distensibilidade",
    "repleção", "repleto", "repleta",
    "colabado", "colabada",
    "dilatado", "dilatada", "dilatação", "dilatações",
    
    // === DESCRITORES NEGATIVOS ===
    "excluir", "excluído", "excluída",
    "descartado", "descartada",
    "afastado", "afastada",
    
    // === ACHADOS/LESÕES ===
    "lesional",
    "focais", "focalmente",
    "difuso", "difusa", "difusos", "difusas",
    "nodular", "nodulares",
    "cistos", "císticos", "císticas",
    "calcificações", "calcificado", "calcificada",
    "microcalcificações",
    "cálculo", "cálculos", "calculosa", "calculosas", "calculoso",
    
    // === TERMOS TÉCNICOS DE EXAME ===
    "sequências", "sequência",
    "multiplanares", "multiplanar",
    "ponderadas", "ponderado", "ponderada",
    "contrastado", "contrastada", "contrastação",
    "paramagnético", "paramagnética",
    "endovenoso", "endovenosa",
    "hepatoespecífico",
    "primovist",
    "gadolínio",
    "iodado",
    "excretora", "excretor",
    "perfusional",
    "difusão", "difusional",
    "angio", "angiorressonância", "angiografia",
    
    // === VERBOS MÉDICOS ESPECÍFICOS ===
    "medem", "medindo",
    "evidenciamos",
    "identifica", "identificado", "identificada", "identificando",
    "caracterizando",
    "demonstrou",
    "observadas",
    "revela", "revelando", "revelado",
    "exibe", "exibindo",
    "nota", "notando",
    "sugestivos",
    "correlacionar", "correlacionado",
    
    // === LOCALIZAÇÃO ===
    "intra", "extra", "peri", "para", "retro", "sub", "supra",
    "intrahepático", "extrahepático",
    "intra-hepáticas", "extra-hepáticas",
    "intracraniano", "intracraniana",
    "intraperitoneal",
    "subcapsular", "extracapsular",
    "periféricos",
    "centrais",
    "proximais",
    "distais",
    "mediais",
    "laterais",
    "anteriores",
    "posteriores",
    "superiores",
    "inferiores",
    
    // === TERMOS DE LAUDO ===
    "limites", "normalidade",
    "complementação",
    "particularidades",
    "métodos",
    "critério", "clínicos",
    
    // === PATOLOGIAS ESPECÍFICAS ===
    "linfonodomegalia", "linfonodomegalias",
    "linfonopatia", "linfonodopatia", "linfonodopatias",
    "linfonodos", "linfonodo",
    "adenopatia", "adenopatias",
    "esteatose", "esteatótico",
    "cirrose", "cirrótico", "cirrótica",
    "hepatopatia",
    "colelitíase", "coledocolitíase",
    "colecistite",
    "pancreatite",
    "pielonefrite",
    "hidronefrose", "pielocalicinal",
    "trombose", "trombo", "trombos",
    "estenose", "estenoses", "estenosado",
    "oclusão", "oclusões", "ocluído",
    "aneurisma", "aneurismas", "aneurismáticas",
    "dissecção", "dissecções",
    "hérnia", "hérnias", "herniado", "herniada",
    "protrusão", "protrusões",
    "fratura", "fraturas",
    "edema", "edematoso", "edematosa",
    "fibrose", "fibrótico", "fibrótica",
    "atrofia", "atrófico", "atrófica",
    
    // === UNIDADES E MEDIDAS ===
    "hu",
    "diâmetro", "diâmetros",
    "eixo", "eixos",
    "volumétrico",
    
    // === TERMOS ESPECÍFICOS POR MODALIDADE ===
    "flair", "stir", "dwi", "adc",
    "t1", "t2",
    "washout", "realce",
    "impregnação",
    "hounsfield", "agatston",
    "janela", "janelas",
    "sombra", "acústica", "acústico",
    "doppler", "fluxo",
    "reforço",
    "artefato", "artefatos",
    "murphy",
    
    // === TERMOS OBSTÉTRICOS ===
    "feto", "fetal", "fetais",
    "gestação", "gestacional",
    "placentário", "placenta",
    "líquido", "amniótico",
    "cordão", "umbilical",
    
    // === OUTROS TERMOS FREQUENTES ===
    "aparentes",
    "avaliado", "avaliada", "avaliados", "avaliadas",
    "padrão", "padrões",
    "distribuição",
    "relação", "proporção",
    "conjunto", "contexto",
    "decorrente", "decorrentes",
    "secundários",
    "eventualmente",
    "sobretudo",
    "poderão",
    "cpre", "colangiorm",
    "ramos", "paredes", "conteúdo", "homogêneo", "meio", "concentração", "conservados", "vias",
    
    // === ANATOMIA/ESTRUTURAS ADICIONAIS ===
    "forma", "formas",
    "arquitetura", "arquitetural",
    "arco", "troncos",
    "bulbo", "bulbos",
    "lobo", "lobos",
    "segmento", "segmentos",
    "espaços",
    "intercostal", "intercostais",
    "membro", "membros",
    "leito",
    
    // === DESCRITORES DE ESTADO/VISUALIZAÇÃO ===
    "visibilizado", "visibilizada", "visibilizados", "visibilizadas",
    "mantido", "mantida", "mantidos",
    "comum", "comuns",
    "interno", "interna", "internos", "internas",
    "significativo", "significativa", "significativos", "significativas",
    "indeterminado", "indeterminada", "indeterminados",
    "acentuado", "acentuada", "acentuados", "acentuadas",
    "rombo", "rombos",
    "maldefinido", "maldefinidos", "maldefinida", "maldefinidas",
    "gorduroso", "gordurosa", "gordurosos", "gordurosas",
    "crônico", "crônica", "crônicos", "crônicas",
    "reduzido", "reduzida", "reduzidos", "reduzidas",
    "solitário", "solitária", "solitários", "solitárias",
    "suspeito", "suspeita", "suspeitos", "suspeitas",
    "comprometido", "comprometida", "comprometidos", "comprometidas", "comprometendo",
    
    // === TERMOS TÉCNICOS DE EXAME ===
    "simetria", "simétrico", "simétrica",
    "alinhamento", "alinhado", "alinhada",
    "aeração",
    "vascularização",
    "restrição",
    "infiltração", "infiltrado", "infiltrada",
    "depósito", "depósitos",
    "extensão",
    "fator", "fatores",
    "obstrutivo", "obstrutiva", "obstrutivos",
    "feixe",
    "grau", "graus",
    "bilateralmente",
    "difusamente",
    
    // === MODALIDADES E TÉCNICAS ===
    "tomografia",
    "ressonância",
    "magnética", "magnético",
    "computadorizada", "computadorizado",
    "convencional",
    "colangiorressonância",
    
    // === STATUS E CONDIÇÕES ===
    "status",
    "cirúrgico", "cirúrgica", "cirúrgicos",
    "pós-cirúrgico", "pós-cirúrgica",
    "pós-colecistectomia",
    
    // === PATOLOGIAS ADICIONAIS ===
    "hemangioma", "hemangiomas",
    
    // === SUBSTÂNCIAS (DOENÇAS DE DEPÓSITO) ===
    "ferro",
    "glicogênio",
    "cobre",
    
    // === OUTROS TERMOS FREQUENTES NOS TEMPLATES ===
    "pacs",
    "ortostase",
    "curva", "curvas",
    "fisiológico", "fisiológica", "fisiológicos", "fisiológicas",
    "laudo", "laudos",
    "elaborado", "elaborada",
    "base", "bases",
    "cerca",
    "disponível", "disponíveis",
    "custa",
    "massas"
  ],
  
  // === TERMOS DE NEURORRADIOLOGIA (EXTRAÍDOS DOS TEMPLATES) ===
  termos_neuro_templates: [
    // ANATOMIA ENCEFÁLICA COMPLEMENTAR
    "supratentorial", "supratentoriais",
    "infratentorial", "infratentoriais",
    "tentório", "tentorial",
    "extra-axial", "extra-axiais",
    "intra-axial", "intra-axiais",
    "centro semioval", "semiovais",
    "periventricular", "periventriculares",
    "quiasma", "quiasmático", "quiasmática",
    "cavernosos", "cavernoso",
    "cávum", "cavuns", "meckel",
    "liquóricos", "liquórico",
    "pericerebrais", "pericerebral",
    "subaracnoideanos", "subaracnoideo", "subaracnoideos",
    "pericerebelar", "pericerebelares",
    "linha média",
    "base do crânio",
    "estruturas ósseas cranianas",
    
    // ANATOMIA VASCULAR INTRACRANIANA
    "artéria basilar", "basilar",
    "artérias cerebrais", "cerebral anterior", "cerebral média", "cerebral posterior",
    "segmentos intradurais", "intradural", "intradurais",
    "seios venosos", "venosos durais",
    "sistema venoso superficial", "sistema venoso profundo",
    "vértebro-basilar", "vértebro basilar",
    "supra-aórticos", "supra-aórtico",
    
    // HIPÓFISE E SELA TÚRCICA
    "adeno-hipófise", "adenohipófise",
    "neuro-hipófise", "neurohipófise",
    "haste hipofisária", "infundíbulo",
    "seios esfenoidais", "esfenoidal", "esfenoidais",
    
    // OUVIDO E OSSO TEMPORAL
    "cócleas", "cóclea", "coclear", "cocleares",
    "canais semicirculares", "semicircular", "semicirculares",
    "vestíbulos", "vestíbulo", "vestibular", "vestibulares",
    "labirinto", "labiríntico", "labiríntica",
    "membranoso", "membranosa",
    "condutos auditivos internos", "conduto auditivo interno",
    "cisternal", "cisternais",
    "intracanalicular", "intracanaliculares",
    "pontocerebelar", "ponto cerebelar",
    "ângulo pontocerebelar", "ângulo ponto cerebelar",
    "pares cranianos", "par craniano",
    "VII par", "VIII par",
    
    // COLUNA E MEDULA (TERMOS ESPECÍFICOS)
    "transição crânio-cervical", "crânio-cervical",
    "interespaços discais", "interespaço discal",
    "interfacetárias", "interfacetária", "interfacetário",
    "interapofisárias", "interapofisária",
    "forames de conjugação", "forame de conjugação",
    "cone medular",
    "cauda equina", "cauda eqüina",
    "raízes nervosas", "raiz nervosa",
    
    // ACHADOS E PATOLOGIAS ESPECÍFICAS
    "microangiopatia", "microangiopático", "microangiopática",
    "isquemia", "isquêmicos",
    "processo expansivo", "processos expansivos",
    "ectasia", "ectásico", "ectásica", "ectasias",
    "intraparenquimatoso", "intraparenquimatosos",
    "compensatória", "compensatório", "compensatórias",
    "pequenos vasos", "doença dos pequenos vasos",
    "fenômenos isquêmicos",
    "redução volumétrica", "volumétrica",
    
    // TERMOS TÉCNICOS DE EXAME
    "ECOPLANAR", "ecoplanar",
    "Spin-Echo", "spin-echo", "spin echo",
    "opacificação", "opacificado", "opacificada",
    "anômala", "anômalo", "anômalas", "anômalos",
    "impregnação anômala",
    "agente paramagnético",
    "angiografia digital", "subtração",
    "critério", "critérios",
    
    // DESCRITORES DE FLUXO
    "fluxo habitual",
    "sinal de fluxo",
    "flow void", "vazio de fluxo"
  ],
  
  // === TERMOS DE TÓRAX E CORAÇÃO (EXTRAÍDOS DOS TEMPLATES) ===
  termos_torax_cardiaco_templates: [
    // ANATOMIA CARDÍACA
    "átrio", "átrios",
    "átrio direito", "átrio esquerdo",
    "ventrículo direito", "ventrículo esquerdo",
    "câmaras cardíacas", "câmaras",
    "miocárdio", "miocárdica", "miocárdico",
    "septo interventricular", "septo interatrial",
    "valva mitral", "valva tricúspide",
    "valva aórtica", "valva pulmonar",
    "anel valvar", "anéis valvares",
    "cordoalhas tendinosas",
    "músculo papilar", "músculos papilares",
    "endocárdio", "endocárdica", "endocárdico",
    "epicárdio", "epicárdica", "epicárdico",
    "pericárdio visceral", "pericárdio parietal",
    "saco pericárdico",
    
    // FUNÇÃO CARDÍACA
    "função sistólica", "sistólica", "sistólico",
    "função diastólica", "diastólica", "diastólico",
    "biventricular",
    "fração de ejeção", "FEVE", "FEVD",
    "IVDFVD", "IVSFVD", "IVDFVE", "IVSFVE", "IVAE",
    "débito cardíaco",
    "contratilidade",
    "hipocinesia", "hipocinético", "hipocinética",
    "acinesia", "acinético", "acinética",
    "discinesia", "discinético", "discinética",
    "normocinético", "normocinética",
    "hipercinético", "hipercinética",
    "segmentar", "segmentares",
    
    // TERMOS DE RM CARDÍACA
    "cine-ressonância", "cine RM", "cine",
    "double IR", "triple IR",
    "mapas T1", "mapas T2", "mapping",
    "técnica MOLLI", "MOLLI",
    "miocardite", "miocardítica", "miocardítico",
    "realce tardio miocárdico",
    "fibrose miocárdica",
    "edema miocárdico",
    "stress cardíaco",
    "perfusão miocárdica",
    
    // ANATOMIA TORÁCICA COMPLEMENTAR
    "parede torácica",
    "corpo do esterno", "corpo esternal",
    "manúbrio esternal", "manúbrio",
    "articulações esternoclaviculares", "esternoclavicular", "esterno-claviculares",
    "junções costocondrais", "costocondral", "costocondrais",
    "junções condroesternais", "condroesternal", "condroesternais",
    "arcos costais", "arco costal",
    "musculares", "muscular",
    "artérias pulmonares",
    "ramos principais", "ramos lobares", "ramos segmentares",
    "tronco pulmonar", "tronco da artéria pulmonar",
    "artéria pulmonar direita", "artéria pulmonar esquerda",
    "hilares", "hilar",
    "peribroncovasculares", "periboncovascular",
    "estruturas ósseas", "estrutura óssea",
    "estruturas vasculares mediastinais",
    
    // TERMOS DESCRITIVOS DE LAUDO
    "dimensões preservadas", "dimensões aumentadas",
    "calibre preservado", "calibre normal",
    "contornos preservados", "contornos normais",
    "topografia normal", "topografia",
    "situação normal",
    "patentes", "patente",
    "centrado", "centrada",
    "atenuação preservada",
    "área cardíaca", "área cardíaca preservada",
    "aspecto preservado",
    "limitações do método",
    
    // TERMOS TÉCNICOS DE EXAME
    "aquisições volumétricas", "aquisição volumétrica",
    "reconstruções multiplanares", "reconstrução multiplanar",
    "janela pulmonar", "janela de pulmão",
    "janela mediastinal", "janela de mediastino",
    "janela óssea", "janela ósseo",
    "fase arterial", "fase venosa",
    "protocolo TEP", "protocolo tromboembolismo",
    "leito vascular",
    "negativa para", "negativo para",
    "angiotomografia", "angiotomográfico", "angiotomográfica",
    "direcionado", "direcionada"
  ],
  
  // === TERMOS DE ABDOME (EXTRAÍDOS DOS TEMPLATES) ===
  termos_abdome_templates: [
    // ANATOMIA ABDOMINAL ESPECÍFICA
    "arquitetura vascular", "ramos portais", "sistema porta",
    "coletores", "sistemas coletores", "pielocaliciais",
    "segmentos", "segmento", "segmentar",
    "córtex renal", "corticomedular", "diferenciação corticomedular",
    "corticais", "adelgaçamento",
    "lúmen", "luminal", "endoluminal", "endoluminais",
    "pelve renal", "pelves", "piélico",
    "espaços", "planos gordurosos", "planos adiposos",
    "leito vesicular",
    "gordura abdominal", "adiposos adjacentes",
    "junção", "junções", "biliopancreática",
    "implantação", "terço médio",
    "espessura do parênquima",
    "bordos rombos", "bordos finos",
    
    // ANATOMIA VASCULAR ABDOMINAL
    "veia cava inferior", "VCI",
    "tributárias", "ramos", "confluência",
    "tronco celíaco",
    "artéria mesentérica", "artérias mesentéricas",
    "mesentérica superior", "mesentérica inferior",
    "artérias renais", "veias renais",
    "esplênica", "gastroesplênica",
    "gástrica", "gastroduodenal",
    "bifurcação", "emergência",
    "suprarrenal", "infrarrenal", "suprarrenais",
    "ápice", "transição tóraco abdominal",
    "segmentos intradurais",
    "pérvios", "pérvia",
    "fluxo habitual", "opacificação",
    
    // TERMOS DE TÉCNICA USG
    "transdutor", "convexo", "multifrequencial",
    "varredura", "sistemática",
    "documentação", "representativas",
    "feixe acústico", "atenuação do feixe",
    "repleção habitual", "ecos",
    "modo bidimensional", "dinâmico",
    "porções posteriores",
    "parcialmente identificado",
    "líquido livre", "livre na cavidade",
    "peritoneal",
    
    // TERMOS DE TÉCNICA TC
    "aquisições volumétricas", "aquisição volumétrica",
    "helicoidal", "multislice",
    "reconstruções", "reformatações", "reformatação",
    "contraste oral", "VO",
    "coeficiente de atenuação",
    "protocolo direcionado",
    "leito vascular", "vascular de interesse",
    "padrão arterial", "padrão portal", "padrão tardio",
    "fases", "fase arterial", "fase portal", "fase tardia",
    "fase excretora", "excreção",
    
    // TERMOS DE TÉCNICA RM
    "sequências multiplanares",
    "intensidade de sinal", "sinal habitual",
    "protocolo esteatose", "protocolo ferro",
    "gordura e ferro hepáticos",
    "contraste paramagnético",
    "concentração adequada",
    
    // DESCRITORES DE ESTADO NORMAL
    "sem particularidades", "particularidade",
    "dignas de nota", "digna de nota",
    "dentro dos limites", "limites da normalidade",
    "aspecto habitual",
    "espessura normal", "capacidade conservada",
    "conteúdo anecóico", "conteúdo homogêneo",
    "calibre normal", "calibre conservado",
    "trajeto preservado", "trajeto normal",
    "sinais aparentes",
    "boa repleção", "baixa repleção",
    "concentrado", "concentração",
    "habitualmente",
    
    // ACHADOS E PATOLOGIAS USG
    "hepatopatia de depósito",
    "Murphy ultrassonográfico",
    "imagem calculosa", "imagens calculosas",
    "delaminadas", "delaminada",
    "hiperdistendida", "hiperdistendido",
    "artefato de reverberação", "reverberação posterior",
    "artefato em cauda de cometa", "cauda de cometa",
    "intramurais", "intramural",
    "ecogênicos intramurais",
    "formadores de sombra", "formadora de sombra",
    "aspecto residual", "residual",
    "à montante", "à jusante",
    
    // DESCRITORES DE RX ABDOME
    "traçado vascular", "traçado",
    "decúbito dorsal", "ortostática",
    "anteroposterior", "AP",
    "nível hidroaéreo", "níveis hidroaéreos",
    "gases distribuídos", "distribuição gasosa",
    "obstrução intestinal", "trânsito intestinal",
    "pneumoperitônio",
    "compressão", "dupla contrastação",
    
    // MEDIDAS E ÍNDICES
    "índice esplênico",
    "maior eixo", "menor eixo",
    "diâmetro transverso", "diâmetro anteroposterior",
    "volume", "volumetria"
  ],
  
  // === TERMOS DE RADIOGRAFIA (EXTRAÍDOS DOS TEMPLATES RX) ===
  termos_radiografia_templates: [
    // COLUNA VERTEBRAL
    "eixo cervical", "eixo dorsal", "eixo lombar", "eixo sacrococcígeo", "eixo vertebral",
    "alinhamento vertebral", "alinhamento vertebral posterior",
    "corpos vertebrais anatômicos",
    "uncovertebrais", "articulações uncovertebrais",
    "pedículos", "pedículo",
    "apófises espinhosas", "apófise espinhosa",
    "costovertebrais", "articulações costovertebrais",
    "curvatura toracolombar", "toracolombar",
    "convexidade esquerda", "convexidade direita", "convexidade",
    "ângulo de Cobb", "Cobb",
    "cifose dorsal", "cifose", "cifótico", "cifótica",
    "lordose lombar", "lordose", "lordótico", "lordótica",
    "listese", "anterolistese", "retrolistese",
    "canal sacral",
    "anteriorização", "segmentos coccígeos", "coccígeo", "coccígea",
    "rarefação óssea", "rarefação",
    
    // CRÂNIO E SELA TÚRCICA
    "processos clinoideos", "clinoideos", "clinoideo",
    "assoalho selar", "infradesnivelamentos", "infradesnivelamento",
    "calcificações carotídeas", "calcificação intraselar",
    "sulcos vasculares", "sulco vascular",
    "junção crânio-cervical",
    "calcificações intracranianas",
    
    // SEIOS DA FACE E NARIZ
    "seios paranasais", "paranasais", "paranasal",
    "seio frontal", "frontal",
    "células etmoidais", "etmoidais", "etmoidal",
    "septos intercelulares", "intercelulares",
    "antros maxilares", "antro maxilar", "antros",
    "septo nasal",
    "fossas nasais", "fossa nasal",
    "arejadas", "arejado", "transparente", "transparentes",
    
    // MANDÍBULA E ATM
    "côndilos mandibulares", "côndilo mandibular", "côndilos",
    "cavidades glenoides", "cavidade glenoide", "glenoides", "glenoide",
    "temporo-mandibulares", "temporo-mandibular",
    
    // ÓRBITAS
    "cavidades orbitárias", "cavidade orbitária",
    "paredes orbitárias", "parede orbitária",
    "corpo estranho", "corpos estranhos",
    
    // CAVUM E RINOFARINGE
    "espaço aéreo", "coluna aérea",
    "parede posterior da nasofaringe",
    "tonsilas palatinas", "tonsila", "tonsilas",
    "rinofaringe",
    
    // OSSOS E ARTICULAÇÕES GERAIS
    "cortical íntegra", "cortical",
    "medula óssea", "medula óssea com densidade preservada",
    "superfícies articulares regulares",
    "partes moles visíveis", "partes moles normais", "partes moles",
    "calcificações periarticulares", "periarticulares",
    
    // OSSOS ESPECÍFICOS
    "ossos do carpo", "carpo",
    "metacarpos", "metacarpo",
    "falanges", "falange", "falangiano", "falangiana",
    "epífises", "epífise",
    "apófises estilóides", "estilóides", "estilóide",
    "arcos zigomáticos", "zigomático", "zigomáticos",
    "osso malar", "malar",
    "espaços intercostais", "intercostais", "intercostal",
    
    // ESCANOMETRIA E IDADE ÓSSEA
    "escanometria",
    "idade óssea", "idade cronológica",
    "ossificação normal", "ossificação",
    
    // ESTUDOS CONTRASTADOS - DIGESTIVO ALTO
    "trânsito faríngeo", "trânsito esofágico",
    "relevo mucoso", "relevo",
    "lesões ulceradas", "ulceradas", "ulcerada",
    "lesões vegetantes", "vegetantes", "vegetante",
    "lesões infiltrantes", "infiltrantes", "infiltrante",
    "piloro pérvio", "piloro",
    "bulbo duodenal", "bulbo",
    "arco duodenal",
    "trânsito digestivo alto",
    
    // ESTUDOS CONTRASTADOS - DIGESTIVO BAIXO
    "trânsito retrógrado",
    "grosso intestino",
    "íleo distal",
    "segmentos cólicos",
    "formações diverticulares", "diverticulares",
    "espaço retro-retal", "retro-retal",
    "enema opaco", "enema",
    
    // SUBSTÂNCIAS CONTRASTADAS
    "bário",
    "contraste iodado", "iodado", "hidrossolúvel",
    "opacificação das estruturas",
    "distensibilidade",
    "enchimento",
    
    // COLANGIOGRAFIA
    "agulha de Chiba", "Chiba",
    "IEC", "hilo hepático",
    "colangiografia transparieto", "transparieto",
    
    // TÉCNICAS E INCIDÊNCIAS
    "incidência", "incidências",
    "penetração", "centro do filme",
    "projeção AP", "projeção PA",
    "perfil", "oblíqua", "oblíquas",
    "transoral",
    "dinâmica", "extensão", "flexão",
    "fronto-naso", "mento-naso",
    "Hirtz", "Bretton", "Zanca", "Ferguson",
    "axial", "axilar",
    "em carga", "com apoio",
    "em rotação", "em pronação",
    "em ortostase", "em decúbito",
    "panorâmica", "panorâmico",
    
    // DESCRITORES DE QUALIDADE
    "boa penetração", "boa distensão",
    "exame tecnicamente limitado",
    "qualidade adequada",
    
    // DESCRITORES ESPECÍFICOS DE RX
    "aspecto radiológico", "aspecto radiológico normal",
    "configuração anatômica", "configuração usual",
    "bem configurados", "bem configurado",
    "sem alterações significativas",
    "sem anormalidades",
    "descontinuidade da estrutura óssea", "descontinuidade",
    "sinais radiológicos",
    "estruturas visibilizadas",
    
    // PATOLOGIAS E ACHADOS RX
    "esclerose óssea", "esclerose",
    "reabsorção óssea", "reabsorção",
    "alterações inflamatórias",
    "redução dos espaços articulares",
    "face ilíaca", "ilíaca", "ilíaco",
    "sacro-ilíacas", "sacroilíacas"
  ],
  
  // === TERMOS DE TOMOGRAFIA COMPUTADORIZADA (EXTRAÍDOS DOS TEMPLATES TC) ===
  termos_tomografia_templates: [
    // ANGIOTOMOGRAFIA E CORONÁRIAS (~50 termos)
    "Agatston", "escore de cálcio", "coronariano", "coronariana", "coronarianas",
    "coronária direita", "coronária esquerda",
    "descendente anterior", "descendente posterior",
    "circunflexa", "circunflexo",
    "diagonal", "diagonalis", "marginal",
    "TCE", "tronco da coronária", "bifurcado",
    "dominante", "dominância",
    "folhetos", "folheto", "coronariano esquerdo", "não coronariano",
    "espículas", "espícula", "cálcicas",
    "sístole", "diástole",
    "perímetro", "óstio", "óstios",
    "bulbo aórtico",
    "arco transverso",
    "junção sinoaórtica", "sinoaórtica",
    "troncos supra-aórticos", "supra-aórticos",
    "braquiocefálico",
    "subclávias", "subclávia",
    "bulbos carotídeos", "bulbo carotídeo",
    "vértebro-basilar",
    "poplítea", "poplíteo",
    "fibular", "fibulares",
    "membros inferiores",
    
    // CRÂNIO E NEUROLOGIA (~35 termos)
    "cavidades ventriculares",
    "largura adequada",
    "ventriculares",
    "pericerebrais", "pericerebral",
    "alargamento", "alargados", "alargado",
    "atrofia leve", "atrofia moderada",
    "semi-oval", "centro semi-oval",
    "hipodensas", "hipodensa",
    "redução do volume", "volume cerebral",
    "microangiopatia isquêmica",
    "neurológica", "neurológico",
    "evolutivo", "controle evolutivo",
    "seios venosos durais",
    "trombose venosa intracraniana",
    "sistema cortical",
    "sistema subcortical",
    
    // FACE, SEIOS E ÓRBITAS (~40 termos)
    "celular subcutâneo", "subcutâneo",
    "infratemporais", "infratemporal",
    "ptérigopalatinas", "ptérigopalatina", "fossas ptérigopalatinas",
    "infundíbulos", "infundíbulo",
    "recessos frontonasais", "frontonasal",
    "esfenoetmoidais", "esfenoetmoidal",
    "meatos nasais", "meato",
    "amplitude",
    "fóveas etmoidais", "fóvea", "fóveas",
    "intraorbitárias", "intraorbitária",
    "mastoides", "mastoide", "mastoideo", "mastoidea",
    "pneumatização", "pneumatizados",
    "timpânica", "timpânico", "cavidade timpânica",
    "antro mastoideo", "antro",
    "Prussak", "espaços de Prussak",
    "esporões", "esporão",
    "cadeia ossicular", "ossicular",
    "janelas ovais", "janela oval",
    "permeáveis", "permeável",
    "condutos auditivos", "conduto auditivo",
    "jugulares", "forames jugulares",
    "carotídeos", "canais carotídeos",
    "glândulas lacrimais", "lacrimal", "lacrimais",
    "musculatura extrínseca", "extrínseca", "extrínseco",
    "extraconais", "extraconal",
    "intraconais", "intraconal",
    "lâminas papiráceas", "papiráceas", "papirácea",
    "deiscências", "deiscência",
    "canais ópticos",
    
    // PESCOÇO (~15 termos)
    "parafaríngeos", "parafaríngeo", "espaços parafaríngeos",
    "parótidas", "parótida", "glândulas parótidas",
    "submandibulares", "submandibular",
    "planos musculares",
    "coeficientes de atenuação",
    
    // COLUNA VERTEBRAL (~20 termos)
    "canal vertebral",
    "alinhamento posterior",
    "interespaços discais", "interespaço discal",
    "protrusões discais", "protrusão discal",
    "interfacetárias", "interfacetária",
    "forames de conjugação", "forame de conjugação",
    "expressivas", "reduções expressivas",
    "transição crânio cervical",
    
    // MUSCULOESQUELÉTICO (~35 termos)
    "osteolíticas", "osteolítica", "lesões osteolíticas",
    "blásticas", "blástica", "lesões blásticas",
    "sínfise púbica", "sínfise",
    "femoroacetabulares", "femoroacetabular", "espaços femoroacetabulares",
    "femorotibiais", "femorotibial", "compartimentos femorotibiais",
    "patelofemoral",
    "glenoumerais", "glenoumeral",
    "acromioclavicular",
    "domus talar", "domus",
    "osteocondral", "lesão osteocondral",
    "coleções", "coleção",
    "partes moles",
    "sensibilidade limitada",
    "salientando", "salientando-se",
    "periarticulares", "periarticular",
    "TA-GT", "TAGT",
    "índice de altura patelar",
    "ângulo troclear",
    "báscula patelar", "báscula",
    "escápula",
    "porção avaliada",
    
    // ABDOME E PELVE (~25 termos)
    "cavidade pélvica",
    "ginecológica", "ginecológico",
    "urológica", "urológico",
    "limitações do método",
    "vesículas seminais",
    "regiões anexiais",
    "moldura cólica",
    "pregueado mucoso", "pregueado",
    "ingurgitamento vascular", "ingurgitamento",
    "linfonodopatia mesentérica",
    "trajetos fistulosos", "fistulosos", "fistuloso",
    "coleções intracavitárias", "intracavitárias",
    "câmara gástrica",
    "arco duodenal",
    "endoluminais", "endoluminal",
    "pregueado",
    
    // TÉCNICAS DE TC (~20 termos)
    "multislice",
    "helicoidal",
    "reformatações", "reformatação",
    "janela pulmonar",
    "janela mediastinal",
    "janela óssea",
    "nefrográfica", "nefrográfico",
    "não iônico", "iônico",
    "equipamento",
    "canais",
    "detalhada",
    "posteriores reformatações",
    "protocolo direcionado",
    "subtração digital",
    "padrão ouro",
    
    // DESCRITORES GERAIS (~20 termos)
    "usual", "usuais",
    "anormalidades", "anormalidade",
    "evidente", "evidentes",
    "evidenciamos",
    "significativas",
    "sugiram",
    "detecção",
    "caracterizam",
    "examinadas", "examinada", "examinado",
    "salientando-se",
    "considerando-se",
    "evidentes ao método"
  ],
  
  sinonimos: {
    aneico: ["anecogênico", "sonolucente", "líquido simples", "conteúdo fluídico"],
    hipoecogênico: ["hipoecóico", "escuro ao ultrassom"],
    hiperecogênico: ["hiperecóico", "brilhante ao ultrassom"],
    hipodenso: ["baixa atenuação", "hipoatenuante", "radiotransparente"],
    hiperdenso: ["alta atenuação", "hiperatenuante", "radiopaco"],
    isodenso: ["isoatenuante"],
    "esteatose hepática": ["fígado gorduroso", "infiltração gordurosa hepática"],
    "derrame pleural": ["efusão pleural", "coleção líquida pleural"],
    "líquido livre": ["ascite", "coleção peritoneal", "efusão abdominal", "líquido ascítico"],
    HNF: ["hiperplasia nodular focal"],
    "placas desmielinizantes": ["lesões de substância branca", "lesões focais brancas"],
    TVP: ["trombose venosa profunda", "flebotrombose"],
    slice: ["corte tomográfico", "fatia de imagem", "corte"],
    quisto: ["cisto", "quiste"],
    "restrição à difusão": ["queda de sinal no mapa ADC e hipersinal no DWI"],
    "flow void": ["ausência de sinal vascular", "sinal de vazio de fluxo"],
    angiografia: ["estudo radiográfico dos vasos", "arteriografia", "venografia"],
    "TC helicoidal": ["tomografia computadorizada com órbita helicoidal", "TC volumétrica"],
    Ultrassonografia: ["ecografia", "US", "sonografia", "ultrassom"],
    pneumoperitônio: ["gás livre subdiafragmático", "pneumatose"],
    atelectasia: ["colapso pulmonar"],
    artrose: ["osteoartrite", "doença articular degenerativa"],
    osteófitos: ["bicos de papagaio"],
    "edema ósseo": ["contusão óssea", "aumento de sinal na medular óssea"],
    gliose: ["sequela isquêmica", "cicatriz cerebral"],
    micronódulo: ["nódulo pequeno"],
    adenopatia: ["linfonodomegalia"],
    calcificação: ["depósito de cálcio"],
    "necrose avascular": ["osteonecrose"]
  }
} as const

