-- ===================================================
-- OpenRouter Multi-Provider Integration
-- ===================================================

-- 1. Insert OpenRouter as new provider
INSERT INTO public.ai_providers (
  name,
  display_name,
  api_base_url,
  api_key_secret_name,
  auth_header,
  auth_prefix,
  is_active,
  supports_streaming,
  supports_batch,
  documentation_url,
  extra_headers
) VALUES (
  'openrouter',
  'OpenRouter (Multi-Provider)',
  'https://openrouter.ai/api/v1',
  'OPENROUTER_API_KEY',
  'Authorization',
  'Bearer ',
  true,
  true,
  false,
  'https://openrouter.ai/docs',
  '{"HTTP-Referer": "https://radreport.app", "X-Title": "RadReport"}'::jsonb
);

-- 2. Get the provider ID for openrouter
DO $$
DECLARE
  openrouter_provider_id uuid;
BEGIN
  SELECT id INTO openrouter_provider_id FROM public.ai_providers WHERE name = 'openrouter';
  
  -- 3. Insert popular models via OpenRouter
  INSERT INTO public.ai_models (
    name,
    provider,
    provider_id,
    api_name,
    model_family,
    description,
    tier,
    is_active,
    is_legacy,
    default_max_tokens,
    context_window,
    max_output_tokens,
    input_cost_per_1m,
    output_cost_per_1m,
    api_base_url,
    api_key_secret_name,
    auth_header,
    auth_prefix,
    supports_temperature,
    supports_reasoning,
    supports_extended_thinking,
    supports_thinking_budget,
    supports_top_p,
    supports_top_k,
    supports_frequency_penalty,
    supports_presence_penalty,
    supports_stop_sequences,
    supports_seed,
    supports_json_mode,
    supports_tools,
    supports_streaming,
    supports_vision
  ) VALUES
  -- GPT-5 via OpenRouter
  (
    'openrouter/openai/gpt-5',
    'openrouter',
    openrouter_provider_id,
    'openai/gpt-5',
    'gpt-5',
    'GPT-5 via OpenRouter - reasoning model',
    'flagship',
    true,
    false,
    4000,
    128000,
    16384,
    3.00,
    12.00,
    'https://openrouter.ai/api/v1',
    'OPENROUTER_API_KEY',
    'Authorization',
    'Bearer ',
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true
  ),
  -- Claude Sonnet 4 via OpenRouter
  (
    'openrouter/anthropic/claude-sonnet-4',
    'openrouter',
    openrouter_provider_id,
    'anthropic/claude-sonnet-4-20250514',
    'claude-4',
    'Claude Sonnet 4 via OpenRouter - high performance',
    'flagship',
    true,
    false,
    4000,
    200000,
    8192,
    3.00,
    15.00,
    'https://openrouter.ai/api/v1',
    'OPENROUTER_API_KEY',
    'Authorization',
    'Bearer ',
    true,
    false,
    true,
    false,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    true
  ),
  -- Gemini 2.5 Flash via OpenRouter (resolve problema de payload)
  (
    'openrouter/google/gemini-2.5-flash',
    'openrouter',
    openrouter_provider_id,
    'google/gemini-2.5-flash-preview-05-20',
    'gemini-2.5',
    'Gemini 2.5 Flash via OpenRouter - normalizado para OpenAI-style',
    'standard',
    true,
    false,
    2000,
    1000000,
    65536,
    0.15,
    0.60,
    'https://openrouter.ai/api/v1',
    'OPENROUTER_API_KEY',
    'Authorization',
    'Bearer ',
    true,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    true
  ),
  -- Gemini 2.5 Pro via OpenRouter
  (
    'openrouter/google/gemini-2.5-pro',
    'openrouter',
    openrouter_provider_id,
    'google/gemini-2.5-pro-preview-06-05',
    'gemini-2.5',
    'Gemini 2.5 Pro via OpenRouter - high capability',
    'flagship',
    true,
    false,
    4000,
    1000000,
    65536,
    2.50,
    15.00,
    'https://openrouter.ai/api/v1',
    'OPENROUTER_API_KEY',
    'Authorization',
    'Bearer ',
    true,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    true
  ),
  -- Llama 3.3 70B via OpenRouter
  (
    'openrouter/meta-llama/llama-3.3-70b-instruct',
    'openrouter',
    openrouter_provider_id,
    'meta-llama/llama-3.3-70b-instruct',
    'llama-3.3',
    'Llama 3.3 70B Instruct via OpenRouter - open source',
    'standard',
    true,
    false,
    2000,
    131072,
    4096,
    0.10,
    0.20,
    'https://openrouter.ai/api/v1',
    'OPENROUTER_API_KEY',
    'Authorization',
    'Bearer ',
    true,
    false,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
    false
  ),
  -- Mistral Large via OpenRouter
  (
    'openrouter/mistralai/mistral-large-2411',
    'openrouter',
    openrouter_provider_id,
    'mistralai/mistral-large-2411',
    'mistral-large',
    'Mistral Large 2411 via OpenRouter - European AI',
    'flagship',
    true,
    false,
    2000,
    128000,
    8192,
    2.00,
    6.00,
    'https://openrouter.ai/api/v1',
    'OPENROUTER_API_KEY',
    'Authorization',
    'Bearer ',
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true
  ),
  -- Qwen 2.5 72B via OpenRouter
  (
    'openrouter/qwen/qwen-2.5-72b-instruct',
    'openrouter',
    openrouter_provider_id,
    'qwen/qwen-2.5-72b-instruct',
    'qwen-2.5',
    'Qwen 2.5 72B Instruct via OpenRouter - multilingual',
    'standard',
    true,
    false,
    2000,
    131072,
    8192,
    0.35,
    0.40,
    'https://openrouter.ai/api/v1',
    'OPENROUTER_API_KEY',
    'Authorization',
    'Bearer ',
    true,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true
  ),
  -- DeepSeek V3 via OpenRouter (excellent for medical reasoning)
  (
    'openrouter/deepseek/deepseek-chat-v3-0324',
    'openrouter',
    openrouter_provider_id,
    'deepseek/deepseek-chat-v3-0324',
    'deepseek-v3',
    'DeepSeek V3 via OpenRouter - excellent reasoning',
    'flagship',
    true,
    false,
    4000,
    64000,
    8192,
    0.14,
    0.28,
    'https://openrouter.ai/api/v1',
    'OPENROUTER_API_KEY',
    'Authorization',
    'Bearer ',
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
    false
  );
END $$;