// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxhbdbovixbptrjrcwbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4aGJkYm92aXhicHRyanJjd2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMzY3MzgsImV4cCI6MjA3ODcxMjczOH0.S4-5DqCkTdT4_j7ZGfwulMHwgIXG_9g1CtahY6qi50Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Singleton pattern to ensure only one Supabase client instance
let supabaseInstance: SupabaseClient<Database> | null = null;

function createSupabaseClient(): SupabaseClient<Database> {
  if (supabaseInstance) {
    return supabaseInstance;
  }

  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true, // Handle OAuth redirects automatically
      flowType: 'pkce', // Use PKCE flow for enhanced OAuth security
      storageKey: 'radreport-auth', // Unique storage key for this application
    },
    global: {
      headers: {
        'x-application-name': 'radreport',
      },
    },
  });

  return supabaseInstance;
}

export const supabase = createSupabaseClient();