// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxhbdbovixbptrjrcwbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4aGJkYm92aXhicHRyanJjd2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMzY3MzgsImV4cCI6MjA3ODcxMjczOH0.S4-5DqCkTdT4_j7ZGfwulMHwgIXG_9g1CtahY6qi50Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});